import { getPlaceValueBin } from './placeValue';
import type { RetroObject } from './types';

// Wikimedia Commons images via Special:FilePath (stable redirect, works in <img> tags)
const WC = (filename: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(filename)}?width=200`;

const RAW: Omit<RetroObject, 'placeValue'>[] = [
  // ─── ONES (1–9) ──────────────────────────────────────────
  {
    id: 'odyssey',
    name: 'Magnavox Odyssey',
    year: 1972, category: 'computer',
    spec: 1,
    specLabel: '1 game chip',
    speech: 'number of game chips',
    factoid: 'The first home console ever sold. No CPU — just transistors and diodes!',
    imageUrl: WC('Magnavox-Odyssey-Console.jpg'),
  },
  {
    id: 'pong',
    name: 'Pong Home Console',
    year: 1975, category: 'arcade',
    spec: 2,
    specLabel: '2 paddles',
    speech: 'number of built-in paddles',
    factoid: 'Pong was Atari\'s first game. The original home version had just 2 paddles wired in!',
    imageUrl: WC('Atari_Pong_Console-Sears_Tele-Games_version.jpg'),
  },
  {
    id: 'virtualboy',
    name: 'Nintendo Virtual Boy',
    year: 1995, category: 'monitor',
    spec: 2,
    specLabel: '2 colors (red + black)',
    speech: 'number of colors on screen',
    factoid: 'The Virtual Boy only displayed red and black — no other colors at all!',
    imageUrl: WC('Virtual-Boy-Set.jpg'),
  },
  {
    id: 'gameboy_shades',
    name: 'Original Game Boy',
    year: 1989, category: 'monitor',
    spec: 4,
    specLabel: '4 shades of green',
    speech: 'number of shades of green on the screen',
    factoid: 'The Game Boy screen had no backlight and only 4 shades of green-gray.',
    imageUrl: WC('Game-Boy-FL.jpg'),
  },
  {
    id: 'atari2600_switches',
    name: 'Atari 2600 (4-Switch)',
    year: 1980, category: 'computer',
    spec: 4,
    specLabel: '4 difficulty switches',
    speech: 'number of external difficulty switches',
    factoid: 'The Atari 2600 had 4 external switches: Reset, Select, and two difficulty toggles for left/right players!',
    imageUrl: WC('Atari-2600-Wood-4Sw-Set.jpg'),
  },
  {
    id: 'nes_buttons',
    name: 'NES Controller',
    year: 1983, category: 'computer',
    spec: 8,
    specLabel: '8 buttons',
    speech: 'number of buttons',
    factoid: 'The NES controller\'s 8 buttons — D-pad, A, B, Start, Select — became the template every gamepad still follows!',
    imageUrl: WC('NES_controller.jpg'),
  },

  // ─── TENS (10–99) ────────────────────────────────────────
  {
    id: 'pong_score',
    name: 'Pong Arcade Cabinet',
    year: 1972, category: 'arcade',
    spec: 21,
    specLabel: '21 point match',
    speech: 'number of points needed to win a match',
    factoid: 'Pong arcade matches were first to 21. Simple enough to learn in 10 seconds!',
    imageUrl: WC('Pong_Cabinet.jpg'),
  },
  {
    id: 'cga_16',
    name: 'CGA Graphics Card',
    year: 1981, category: 'monitor',
    spec: 16,
    specLabel: '16 colors',
    speech: 'number of colors in the palette',
    factoid: 'CGA was IBM\'s first color graphics standard. 16 colors — enough for classics like King\'s Quest!',
    imageUrl: WC('CGA_Display_Version_2.png'),
  },
  {
    id: 'atari5200_colors',
    name: 'Atari 5200',
    year: 1982, category: 'monitor',
    spec: 27,
    specLabel: '27 on-screen colors',
    speech: 'number of colors displayable at once',
    factoid: 'The Atari 5200 could display 27 colors at once from its 256-color palette.',
    imageUrl: WC('Atari-5200-4P-Set.jpg'),
  },
  {
    id: 'nes_palette',
    name: 'Nintendo NES',
    year: 1983, category: 'monitor',
    spec: 54,
    specLabel: '54 colors in palette',
    speech: 'number of unique colors in the palette',
    factoid: 'The NES could only show 54 unique colors — but programmers used them brilliantly!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'ega_64',
    name: 'EGA Graphics Card',
    year: 1984, category: 'monitor',
    spec: 64,
    specLabel: '64 colors in palette',
    speech: 'number of colors in the palette',
    factoid: 'EGA\'s 64-color palette was a huge leap from CGA\'s 16. Games suddenly looked amazing!',
    imageUrl: WC('EGA_card.jpg'),
  },
  {
    id: 'snes_buttons',
    name: 'SNES Controller',
    year: 1990, category: 'computer',
    spec: 12,
    specLabel: '12 buttons',
    speech: 'number of buttons',
    factoid: 'The SNES controller introduced the L/R shoulder buttons and 4-color diamond face buttons — still the standard today!',
    imageUrl: WC('SNES-Controller.jpg'),
  },

  // ─── HUNDREDS (100–999) ──────────────────────────────────
  {
    id: 'atari2600',
    name: 'Atari 2600',
    year: 1977, category: 'computer',
    spec: 128,
    specLabel: '128 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Atari 2600 had only 128 bytes of RAM — less than a single tweet!',
    imageUrl: WC('Atari-2600-Wood-4Sw-Set.jpg'),
  },
  {
    id: 'intellivision',
    name: 'Mattel Intellivision',
    year: 1979, category: 'computer',
    spec: 352,
    specLabel: '352 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Mattel\'s Intellivision had a tiny 352 bytes of RAM but gorgeous graphics for its time.',
    imageUrl: WC('Intellivision-Console-Set.jpg'),
  },
  {
    id: 'vga_256',
    name: 'VGA Graphics Card',
    year: 1987, category: 'monitor',
    spec: 256,
    specLabel: '256 colors on screen',
    speech: 'number of colors displayable at once',
    factoid: 'VGA\'s 256-color mode powered countless classic PC games including DOOM and DOOM II!',
    imageUrl: WC('VGA_card_with_heat_sink.jpg'),
  },
  {
    id: 'ataryst_colors',
    name: 'Atari ST',
    year: 1985, category: 'monitor',
    spec: 512,
    specLabel: '512 color palette',
    speech: 'number of colors in the full palette',
    factoid: 'The Atari ST had a 512-color palette — though only 16 could show at once in most modes!',
    imageUrl: WC('Atari_1040STf.jpg'),
  },
  {
    id: 'breakout_score',
    name: 'Breakout Cabinet',
    year: 1976, category: 'arcade',
    spec: 864,
    specLabel: '864 max score',
    speech: 'maximum possible score',
    factoid: 'Breakout\'s max score was 864 points. Steve Jobs and Steve Wozniak both worked on it!',
    imageUrl: WC('Breakout2600.jpg'),
  },
  {
    id: 'gb_resolution',
    name: 'Game Boy Screen',
    year: 1989, category: 'monitor',
    spec: 160,
    specLabel: '160 px screen width',
    speech: 'screen width in pixels',
    factoid: 'The Game Boy\'s tiny 160×144 screen was small but sharp enough for Tetris, Pokémon, and Metroid!',
    imageUrl: WC('Game-Boy-FL.jpg'),
  },

  // ─── THOUSANDS (1,000–9,999) ─────────────────────────────
  {
    id: 'intel4004',
    name: 'Intel 4004 CPU',
    year: 1971, category: 'chip',
    spec: 2300,
    specLabel: '2,300 transistors',
    speech: 'number of transistors',
    factoid: 'The 4004 was the world\'s first commercial microprocessor — it powered a calculator!',
    imageUrl: WC('Intel_C4004.jpg'),
  },
  {
    id: 'mos6502',
    name: 'MOS 6502 CPU',
    year: 1975, category: 'chip',
    spec: 3510,
    specLabel: '3,510 transistors',
    speech: 'number of transistors',
    factoid: 'The 6502 powered the Apple II, Atari 2600, NES, and Commodore 64. A true legend!',
    imageUrl: WC('KL_MOS_6502.jpg'),
  },
  {
    id: 'atari2600_cart',
    name: 'Atari 2600 Cartridge',
    year: 1977, category: 'cartridge',
    spec: 4096,
    specLabel: '4,096 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Space Invaders fit into just 4,096 bytes — smaller than many email attachments today!',
    imageUrl: WC('Atari-2600-Cartridge-FL.jpg'),
  },
  {
    id: 'amiga_ham',
    name: 'Amiga 1000 HAM Mode',
    year: 1985, category: 'monitor',
    spec: 4096,
    specLabel: '4,096 colors on screen',
    speech: 'number of colors displayable at once',
    factoid: 'Amiga\'s Hold-And-Modify mode squeezed 4,096 colors onto screen — blew everyone\'s minds in 1985!',
    imageUrl: WC('Amiga_1000DP.jpg'),
  },
  {
    id: 'z80',
    name: 'Zilog Z80 CPU',
    year: 1976, category: 'chip',
    spec: 8500,
    specLabel: '8,500 transistors',
    speech: 'number of transistors',
    factoid: 'The Z80 powered the ZX Spectrum, ColecoVision, and early arcade games like Pac-Man.',
    imageUrl: WC('Zilog_Z80.jpg'),
  },
  {
    id: 'spaceinvaders_max',
    name: 'Space Invaders Cabinet',
    year: 1978, category: 'arcade',
    spec: 9990,
    specLabel: '9,990 max score',
    speech: 'maximum possible score',
    factoid: 'Space Invaders invented the high score table — before it, games just reset to zero!',
    imageUrl: WC('SpaceInvaders-Cocktail-Bally-Midway.jpg'),
  },
  {
    id: 'apple1',
    name: 'Apple I',
    year: 1976, category: 'computer',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Steve Wozniak hand-built the Apple I in his garage. Only 200 were ever made!',
    imageUrl: WC('Apple_I_Computer.jpg'),
  },

  // ─── TEN-THOUSANDS (10,000–99,999) ───────────────────────
  {
    id: 'c64',
    name: 'Commodore 64',
    year: 1982, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Commodore 64 is the best-selling personal computer model of all time — over 17 million sold!',
    imageUrl: WC('Commodore-64-Computer-FL.jpg'),
  },
  {
    id: 'zxspectrum',
    name: 'ZX Spectrum 48K',
    year: 1982, category: 'computer',
    spec: 49152,
    specLabel: '49,152 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Clive Sinclair\'s ZX Spectrum ignited the UK bedroom-coding revolution of the 80s.',
    imageUrl: WC('ZXSpectrum48k.jpg'),
  },
  {
    id: 'intel8086',
    name: 'Intel 8086 CPU',
    year: 1978, category: 'chip',
    spec: 29000,
    specLabel: '29,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 8086 launched the x86 architecture that still powers most PCs and laptops today!',
    imageUrl: WC('Intel_C8086.jpg'),
  },
  {
    id: 'mc68000',
    name: 'Motorola 68000 CPU',
    year: 1979, category: 'chip',
    spec: 68000,
    specLabel: '68,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 68000 powered the Mac, Amiga, Atari ST, and Sega Genesis. A true workhorse!',
    imageUrl: WC('KL_Motorola_68000.jpg'),
  },
  {
    id: 'nes_cart',
    name: 'Super Mario Bros. Cart',
    year: 1985, category: 'cartridge',
    spec: 32768,
    specLabel: '32,768 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Super Mario Bros. fit in 32,768 bytes — about the size of a short Word document!',
    imageUrl: WC('Super-Mario-Bros-Cartridge.jpg'),
  },
  {
    id: 'svga',
    name: 'SVGA 16-bit Color',
    year: 1989, category: 'monitor',
    spec: 65536,
    specLabel: '65,536 colors',
    speech: 'number of displayable colors',
    factoid: '65,536 colors (16-bit "High Color") made SVGA screens look almost photographic!',
    imageUrl: WC('SVGA_Card.jpg'),
  },
  {
    id: 'trs80',
    name: 'TRS-80 Model III',
    year: 1980, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The TRS-80 was nicknamed the "Trash-80" by hobbyists — but it sold 200,000 units!',
    imageUrl: WC('TRS-80_Model_III.jpg'),
  },

  // ─── HUNDRED-THOUSANDS (100,000–999,999) ─────────────────
  {
    id: 'mac128k',
    name: 'Macintosh 128K',
    year: 1984, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The first Mac cost $2,495 in 1984 — nearly $8,000 today. And it only had 128K of RAM!',
    imageUrl: WC('Macintosh128k.jpg'),
  },
  {
    id: 'intel286',
    name: 'Intel 286 CPU',
    year: 1982, category: 'chip',
    spec: 134000,
    specLabel: '134,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 286 could run multiple programs at once — mind-blowing multitasking in 1982!',
    imageUrl: WC('Intel_80286.jpg'),
  },
  {
    id: 'intel386',
    name: 'Intel 386 CPU',
    year: 1985, category: 'chip',
    spec: 275000,
    specLabel: '275,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 386 introduced 32-bit computing to PCs and defined the late-80s power machine.',
    imageUrl: WC('KL_Intel_i386DX.jpg'),
  },
  {
    id: 'amiga500',
    name: 'Amiga 500',
    year: 1987, category: 'computer',
    spec: 524288,
    specLabel: '524,288 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Amiga 500 had better graphics and sound than most competitors for years.',
    imageUrl: WC('Amiga500_system.jpg'),
  },
  {
    id: 'snes_cart',
    name: 'Super Mario World Cart',
    year: 1990, category: 'cartridge',
    spec: 524288,
    specLabel: '524,288 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Super Mario World shipped on a 512K cart — and launched an entire console generation!',
    imageUrl: WC('Super-Mario-World-Box.jpg'),
  },
  {
    id: 'ibmpcxt',
    name: 'IBM PC XT',
    year: 1983, category: 'computer',
    spec: 640000,
    specLabel: '640,000 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: '"640K ought to be enough for anybody" — a quote often misattributed to Bill Gates!',
    imageUrl: WC('IBM_Personal_Computer_XT.jpg'),
  },
  {
    id: 'tetris_wr',
    name: 'NES Tetris',
    year: 1989, category: 'arcade',
    spec: 999999,
    specLabel: '999,999 max score',
    speech: 'maximum possible score',
    factoid: 'NES Tetris maxes out at 999,999 — reaching it is considered a "perfect" game!',
    imageUrl: WC('Tetris_Gameplay.png'),
  },
  {
    id: 'vga_resolution',
    name: 'VGA Monitor (640×480)',
    year: 1987, category: 'monitor',
    spec: 307200,
    specLabel: '307,200 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'VGA\'s 640×480 standard (307,200 pixels) became the baseline PC resolution for a decade.',
    imageUrl: WC('VGA_card_with_heat_sink.jpg'),
  },

  // ─── MILLIONS (1,000,000+) ────────────────────────────────
  {
    id: 'mac_plus',
    name: 'Macintosh Plus',
    year: 1986, category: 'computer',
    spec: 1048576,
    specLabel: '1,048,576 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: '1,048,576 bytes = exactly 1 megabyte. The Mac Plus was the first truly useful Mac!',
    imageUrl: WC('Macintosh_Plus.jpg'),
  },
  {
    id: 'intel486',
    name: 'Intel 486 CPU',
    year: 1989, category: 'chip',
    spec: 1200000,
    specLabel: '1,200,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 486 was so fast it ran DOOM — the game that changed everything.',
    imageUrl: WC('Intel486DX2chip.jpg'),
  },
  {
    id: 'donkeykong_wr',
    name: 'Donkey Kong Cabinet',
    year: 1981, category: 'arcade',
    spec: 1272700,
    specLabel: '1,272,700 world record',
    speech: 'all-time world record score',
    factoid: 'The Donkey Kong world record battle was documented in "The King of Kong" (2007)!',
    imageUrl: WC('Donkey_Kong_arcade_game.jpg'),
  },
  {
    id: 'sxga_monitor',
    name: 'SXGA Monitor (1280×1024)',
    year: 1996, category: 'monitor',
    spec: 1310720,
    specLabel: '1,310,720 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'SXGA\'s 1280×1024 resolution (1.3 megapixels) was the first "high-res" standard for desktops.',
    imageUrl: WC('Dell_1901FP_monitor.jpg'),
  },
  {
    id: 'pacman_perfect',
    name: 'Pac-Man Cabinet',
    year: 1980, category: 'arcade',
    spec: 3333360,
    specLabel: '3,333,360 perfect score',
    speech: 'perfect game score',
    factoid: 'A "perfect" Pac-Man means eating every dot, energizer, ghost, and fruit on all 256 levels!',
    imageUrl: WC('Pac-man_arcade_game.jpg'),
  },
  {
    id: 'genesis_vram',
    name: 'Sega Genesis / Mega Drive',
    year: 1988, category: 'computer',
    spec: 1048576,
    specLabel: '1,048,576 bytes RAM',
    speech: 'total number of bytes of RAM',
    factoid: 'Sega dared players to "do what Nintendon\'t" — and the Genesis had a full megabyte of RAM!',
    imageUrl: WC('Sega-Genesis-Mk1-Console-Set.jpg'),
  },
  {
    id: 'intel_pentium',
    name: 'Intel Pentium CPU',
    year: 1993, category: 'chip',
    spec: 3100000,
    specLabel: '3,100,000 transistors',
    speech: 'number of transistors',
    factoid: 'The Pentium had 3.1 million transistors — and became the chip that defined the 1990s PC.',
    imageUrl: WC('KL_Intel_Pentium_A80501.jpg'),
  },
];

// Validate all specs and attach placeValue
export const RETRO_OBJECTS: RetroObject[] = RAW.map(obj => ({
  ...obj,
  placeValue: getPlaceValueBin(obj.spec),
}));

// Helper: get objects valid for currently unlocked bins
export function getObjectsForBins(unlockedBins: string[]): RetroObject[] {
  return RETRO_OBJECTS.filter(obj => unlockedBins.includes(obj.placeValue));
}

// Weighted-random object picker (avoids repeating last 3)
export function pickNextObject(
  unlockedBins: string[],
  recentIds: string[] = []
): RetroObject {
  const pool = getObjectsForBins(unlockedBins).filter(o => !recentIds.includes(o.id));
  if (pool.length === 0) return getObjectsForBins(unlockedBins)[0];
  return pool[Math.floor(Math.random() * pool.length)];
}
