import { getPlaceValueBin } from './placeValue';
import type { RetroObject } from './types';

// Wikimedia Commons images via Special:FilePath (stable redirect, works in <img> tags)
const WC = (filename: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(filename)}?width=200`;

const RAW: Omit<RetroObject, 'placeValue'>[] = [
  // ─── ONES (1–9) ──────────────────────────────────────────
  {
    id: 'odyssey',
    name: 'Magnavox Odyssey',
    year: 1972, category: 'computer',
    spec: 1,
    specLabel: '1 game chip',
    speech: 'number of game chips',
    factoid: 'The first home console ever sold. No CPU — just transistors and diodes!',
    imageUrl: WC('Magnavox-Odyssey-Console.jpg'),
  },
  {
    id: 'pong',
    name: 'Pong Home Console',
    year: 1975, category: 'arcade',
    spec: 2,
    specLabel: '2 paddles',
    speech: 'number of built-in paddles',
    factoid: 'Pong was Atari\'s first game. The original home version had just 2 paddles wired in!',
    imageUrl: WC('Atari_Pong_Console-Sears_Tele-Games_version.jpg'),
  },
  {
    id: 'virtualboy',
    name: 'Nintendo Virtual Boy',
    year: 1995, category: 'monitor',
    spec: 2,
    specLabel: '2 colors (red + black)',
    speech: 'number of colors on screen',
    factoid: 'The Virtual Boy only displayed red and black — no other colors at all!',
    imageUrl: WC('Virtual-Boy-Set.jpg'),
  },
  {
    id: 'gameboy_shades',
    name: 'Original Game Boy',
    year: 1989, category: 'monitor',
    spec: 4,
    specLabel: '4 shades of green',
    speech: 'number of shades of green on the screen',
    factoid: 'The Game Boy screen had no backlight and only 4 shades of green-gray.',
    imageUrl: WC('Game-Boy-FL.jpg'),
  },
  {
    id: 'atari2600_switches',
    name: 'Atari 2600 (4-Switch)',
    year: 1980, category: 'computer',
    spec: 4,
    specLabel: '4 difficulty switches',
    speech: 'number of external difficulty switches',
    factoid: 'The Atari 2600 had 4 external switches: Reset, Select, and two difficulty toggles for left/right players!',
    imageUrl: WC('Atari-2600-Wood-4Sw-Set.jpg'),
  },
  {
    id: 'nes_buttons',
    name: 'NES Controller',
    year: 1983, category: 'computer',
    spec: 8,
    specLabel: '8 buttons',
    speech: 'number of buttons',
    factoid: 'The NES controller\'s 8 buttons — D-pad, A, B, Start, Select — became the template every gamepad still follows!',
    imageUrl: WC('NES_controller.jpg'),
  },

  // ─── TENS (10–99) ────────────────────────────────────────
  {
    id: 'pong_score',
    name: 'Pong Arcade Cabinet',
    year: 1972, category: 'arcade',
    spec: 21,
    specLabel: '21 point match',
    speech: 'number of points needed to win a match',
    factoid: 'Pong arcade matches were first to 21. Simple enough to learn in 10 seconds!',
    imageUrl: WC('Pong_Cabinet.jpg'),
  },
  {
    id: 'cga_16',
    name: 'CGA Graphics Card',
    year: 1981, category: 'monitor',
    spec: 16,
    specLabel: '16 colors',
    speech: 'number of colors in the palette',
    factoid: 'CGA was IBM\'s first color graphics standard. 16 colors — enough for classics like King\'s Quest!',
    imageUrl: WC('CGA_Display_Version_2.png'),
  },
  {
    id: 'atari5200_colors',
    name: 'Atari 5200',
    year: 1982, category: 'monitor',
    spec: 27,
    specLabel: '27 on-screen colors',
    speech: 'number of colors displayable at once',
    factoid: 'The Atari 5200 could display 27 colors at once from its 256-color palette.',
    imageUrl: WC('Atari-5200-4P-Set.jpg'),
  },
  {
    id: 'nes_palette',
    name: 'Nintendo NES',
    year: 1983, category: 'monitor',
    spec: 54,
    specLabel: '54 colors in palette',
    speech: 'number of unique colors in the palette',
    factoid: 'The NES could only show 54 unique colors — but programmers used them brilliantly!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'ega_64',
    name: 'EGA Graphics Card',
    year: 1984, category: 'monitor',
    spec: 64,
    specLabel: '64 colors in palette',
    speech: 'number of colors in the palette',
    factoid: 'EGA\'s 64-color palette was a huge leap from CGA\'s 16. Games suddenly looked amazing!',
    imageUrl: WC('EGA_card.jpg'),
  },
  {
    id: 'snes_buttons',
    name: 'SNES Controller',
    year: 1990, category: 'computer',
    spec: 12,
    specLabel: '12 buttons',
    speech: 'number of buttons',
    factoid: 'The SNES controller introduced the L/R shoulder buttons and 4-color diamond face buttons — still the standard today!',
    imageUrl: WC('SNES-Controller.jpg'),
  },

  // ─── HUNDREDS (100–999) ──────────────────────────────────
  {
    id: 'atari2600',
    name: 'Atari 2600',
    year: 1977, category: 'computer',
    spec: 128,
    specLabel: '128 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Atari 2600 had only 128 bytes of RAM — less than a single tweet!',
    imageUrl: WC('Atari-2600-Wood-4Sw-Set.jpg'),
  },
  {
    id: 'intellivision',
    name: 'Mattel Intellivision',
    year: 1979, category: 'computer',
    spec: 352,
    specLabel: '352 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Mattel\'s Intellivision had a tiny 352 bytes of RAM but gorgeous graphics for its time.',
    imageUrl: WC('Intellivision-Console-Set.jpg'),
  },
  {
    id: 'vga_256',
    name: 'VGA Graphics Card',
    year: 1987, category: 'monitor',
    spec: 256,
    specLabel: '256 colors on screen',
    speech: 'number of colors displayable at once',
    factoid: 'VGA\'s 256-color mode powered countless classic PC games including DOOM and DOOM II!',
    imageUrl: WC('VGA_card_with_heat_sink.jpg'),
  },
  {
    id: 'ataryst_colors',
    name: 'Atari ST',
    year: 1985, category: 'monitor',
    spec: 512,
    specLabel: '512 color palette',
    speech: 'number of colors in the full palette',
    factoid: 'The Atari ST had a 512-color palette — though only 16 could show at once in most modes!',
    imageUrl: WC('Atari_1040STf.jpg'),
  },
  {
    id: 'breakout_score',
    name: 'Breakout Cabinet',
    year: 1976, category: 'arcade',
    spec: 864,
    specLabel: '864 max score',
    speech: 'maximum possible score',
    factoid: 'Breakout\'s max score was 864 points. Steve Jobs and Steve Wozniak both worked on it!',
    imageUrl: WC('Breakout2600.jpg'),
  },
  {
    id: 'gb_resolution',
    name: 'Game Boy Screen',
    year: 1989, category: 'monitor',
    spec: 160,
    specLabel: '160 px screen width',
    speech: 'screen width in pixels',
    factoid: 'The Game Boy\'s tiny 160×144 screen was small but sharp enough for Tetris, Pokémon, and Metroid!',
    imageUrl: WC('Game-Boy-FL.jpg'),
  },

  // ─── THOUSANDS (1,000–9,999) ─────────────────────────────
  {
    id: 'intel4004',
    name: 'Intel 4004 CPU',
    year: 1971, category: 'chip',
    spec: 2300,
    specLabel: '2,300 transistors',
    speech: 'number of transistors',
    factoid: 'The 4004 was the world\'s first commercial microprocessor — it powered a calculator!',
    imageUrl: WC('Intel_C4004.jpg'),
  },
  {
    id: 'mos6502',
    name: 'MOS 6502 CPU',
    year: 1975, category: 'chip',
    spec: 3510,
    specLabel: '3,510 transistors',
    speech: 'number of transistors',
    factoid: 'The 6502 powered the Apple II, Atari 2600, NES, and Commodore 64. A true legend!',
    imageUrl: WC('KL_MOS_6502.jpg'),
  },
  {
    id: 'atari2600_cart',
    name: 'Atari 2600 Cartridge',
    year: 1977, category: 'cartridge',
    spec: 4096,
    specLabel: '4,096 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Space Invaders fit into just 4,096 bytes — smaller than many email attachments today!',
    imageUrl: WC('Atari-2600-Cartridge-FL.jpg'),
  },
  {
    id: 'amiga_ham',
    name: 'Amiga 1000 HAM Mode',
    year: 1985, category: 'monitor',
    spec: 4096,
    specLabel: '4,096 colors on screen',
    speech: 'number of colors displayable at once',
    factoid: 'Amiga\'s Hold-And-Modify mode squeezed 4,096 colors onto screen — blew everyone\'s minds in 1985!',
    imageUrl: WC('Amiga_1000DP.jpg'),
  },
  {
    id: 'z80',
    name: 'Zilog Z80 CPU',
    year: 1976, category: 'chip',
    spec: 8500,
    specLabel: '8,500 transistors',
    speech: 'number of transistors',
    factoid: 'The Z80 powered the ZX Spectrum, ColecoVision, and early arcade games like Pac-Man.',
    imageUrl: WC('Zilog_Z80.jpg'),
  },
  {
    id: 'spaceinvaders_max',
    name: 'Space Invaders Cabinet',
    year: 1978, category: 'arcade',
    spec: 9990,
    specLabel: '9,990 max score',
    speech: 'maximum possible score',
    factoid: 'Space Invaders invented the high score table — before it, games just reset to zero!',
    imageUrl: WC('SpaceInvaders-Cocktail-Bally-Midway.jpg'),
  },
  {
    id: 'apple1',
    name: 'Apple I',
    year: 1976, category: 'computer',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Steve Wozniak hand-built the Apple I in his garage. Only 200 were ever made!',
    imageUrl: WC('Apple_I_Computer.jpg'),
  },

  // ─── TEN-THOUSANDS (10,000–99,999) ───────────────────────
  {
    id: 'c64',
    name: 'Commodore 64',
    year: 1982, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Commodore 64 is the best-selling personal computer model of all time — over 17 million sold!',
    imageUrl: WC('Commodore-64-Computer-FL.jpg'),
  },
  {
    id: 'zxspectrum',
    name: 'ZX Spectrum 48K',
    year: 1982, category: 'computer',
    spec: 49152,
    specLabel: '49,152 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Clive Sinclair\'s ZX Spectrum ignited the UK bedroom-coding revolution of the 80s.',
    imageUrl: WC('ZXSpectrum48k.jpg'),
  },
  {
    id: 'intel8086',
    name: 'Intel 8086 CPU',
    year: 1978, category: 'chip',
    spec: 29000,
    specLabel: '29,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 8086 launched the x86 architecture that still powers most PCs and laptops today!',
    imageUrl: WC('Intel_C8086.jpg'),
  },
  {
    id: 'mc68000',
    name: 'Motorola 68000 CPU',
    year: 1979, category: 'chip',
    spec: 68000,
    specLabel: '68,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 68000 powered the Mac, Amiga, Atari ST, and Sega Genesis. A true workhorse!',
    imageUrl: WC('KL_Motorola_68000.jpg'),
  },
  {
    id: 'nes_cart',
    name: 'Super Mario Bros. Cart',
    year: 1985, category: 'cartridge',
    spec: 32768,
    specLabel: '32,768 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Super Mario Bros. fit in 32,768 bytes — about the size of a short Word document!',
    imageUrl: WC('Super-Mario-Bros-Cartridge.jpg'),
  },
  {
    id: 'svga',
    name: 'SVGA 16-bit Color',
    year: 1989, category: 'monitor',
    spec: 65536,
    specLabel: '65,536 colors',
    speech: 'number of displayable colors',
    factoid: '65,536 colors (16-bit "High Color") made SVGA screens look almost photographic!',
    imageUrl: WC('SVGA_Card.jpg'),
  },
  {
    id: 'trs80',
    name: 'TRS-80 Model III',
    year: 1980, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The TRS-80 was nicknamed the "Trash-80" by hobbyists — but it sold 200,000 units!',
    imageUrl: WC('TRS-80_Model_III.jpg'),
  },

  // ─── HUNDRED-THOUSANDS (100,000–999,999) ─────────────────
  {
    id: 'mac128k',
    name: 'Macintosh 128K',
    year: 1984, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The first Mac cost $2,495 in 1984 — nearly $8,000 today. And it only had 128K of RAM!',
    imageUrl: WC('Macintosh128k.jpg'),
  },
  {
    id: 'intel286',
    name: 'Intel 286 CPU',
    year: 1982, category: 'chip',
    spec: 134000,
    specLabel: '134,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 286 could run multiple programs at once — mind-blowing multitasking in 1982!',
    imageUrl: WC('Intel_80286.jpg'),
  },
  {
    id: 'intel386',
    name: 'Intel 386 CPU',
    year: 1985, category: 'chip',
    spec: 275000,
    specLabel: '275,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 386 introduced 32-bit computing to PCs and defined the late-80s power machine.',
    imageUrl: WC('KL_Intel_i386DX.jpg'),
  },
  {
    id: 'amiga500',
    name: 'Amiga 500',
    year: 1987, category: 'computer',
    spec: 524288,
    specLabel: '524,288 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Amiga 500 had better graphics and sound than most competitors for years.',
    imageUrl: WC('Amiga500_system.jpg'),
  },
  {
    id: 'snes_cart',
    name: 'Super Mario World Cart',
    year: 1990, category: 'cartridge',
    spec: 524288,
    specLabel: '524,288 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Super Mario World shipped on a 512K cart — and launched an entire console generation!',
    imageUrl: WC('Super-Mario-World-Box.jpg'),
  },
  {
    id: 'ibmpcxt',
    name: 'IBM PC XT',
    year: 1983, category: 'computer',
    spec: 640000,
    specLabel: '640,000 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: '"640K ought to be enough for anybody" — a quote often misattributed to Bill Gates!',
    imageUrl: WC('IBM_Personal_Computer_XT.jpg'),
  },
  {
    id: 'tetris_wr',
    name: 'NES Tetris',
    year: 1989, category: 'arcade',
    spec: 999999,
    specLabel: '999,999 max score',
    speech: 'maximum possible score',
    factoid: 'NES Tetris maxes out at 999,999 — reaching it is considered a "perfect" game!',
    imageUrl: WC('Tetris_Gameplay.png'),
  },
  {
    id: 'vga_resolution',
    name: 'VGA Monitor (640×480)',
    year: 1987, category: 'monitor',
    spec: 307200,
    specLabel: '307,200 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'VGA\'s 640×480 standard (307,200 pixels) became the baseline PC resolution for a decade.',
    imageUrl: WC('VGA_card_with_heat_sink.jpg'),
  },

  // ─── NEW BATCH ───────────────────────────────────────────

  // ── ONES (new) ───────────────────────────────────────────
  {
    id: 'game_watch',
    name: 'Nintendo Game & Watch',
    year: 1980, category: 'computer',
    spec: 1,
    specLabel: '1 built-in game',
    speech: 'number of built-in games',
    factoid: 'Game & Watch handhelds each came with exactly 1 game, forever. Nintendo sold over 43 million units across 59 different titles!',
    imageUrl: WC('Game_and_Watch_Ball.jpg'),
  },
  {
    id: 'nes_channels',
    name: 'NES APU',
    year: 1983, category: 'chip',
    spec: 5,
    specLabel: '5 sound channels',
    speech: 'number of sound channels',
    factoid: 'The NES Audio Processing Unit had 5 channels: 2 pulse waves, 1 triangle, 1 noise, and 1 DMC sampler — all used brilliantly by Koji Kondo!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'atari_st_channels',
    name: 'Atari ST YM2149',
    year: 1985, category: 'chip',
    spec: 3,
    specLabel: '3 sound channels',
    speech: 'number of sound channels',
    factoid: 'The Atari ST\'s YM2149 sound chip had just 3 channels — but demoscene musicians turned those 3 voices into an entire genre of chiptune music!',
    imageUrl: WC('Atari_1040STf.jpg'),
  },
  {
    id: 'gameboy_cpu_mhz',
    name: 'Game Boy CPU',
    year: 1989, category: 'chip',
    spec: 4,
    specLabel: '4 MHz clock speed',
    speech: 'clock speed in megahertz',
    factoid: 'The Game Boy\'s Sharp LR35902 ran at just 4 MHz — slower than your microwave\'s display chip! Yet it delivered Tetris and Pokémon flawlessly.',
    imageUrl: WC('Game-Boy-FL.jpg'),
  },
  {
    id: 'amiga_audio_channels',
    name: 'Amiga Paula Chip',
    year: 1985, category: 'chip',
    spec: 4,
    specLabel: '4 audio channels',
    speech: 'number of audio channels',
    factoid: 'The Amiga\'s Paula chip provided 4-channel 8-bit stereo audio in 1985 — most PCs wouldn\'t match that quality until the Sound Blaster era, five years later!',
    imageUrl: WC('Amiga_1000DP.jpg'),
  },

  // ── TENS (new) ────────────────────────────────────────────
  {
    id: 'fairchild_ram',
    name: 'Fairchild Channel F',
    year: 1976, category: 'computer',
    spec: 64,
    specLabel: '64 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Channel F was the first console to use swappable cartridges — and it squeezed everything into just 64 bytes of RAM!',
    imageUrl: WC('Fairchild-Channel-F-Console-Set.jpg'),
  },
  {
    id: 'colecovision_colors',
    name: 'ColecoVision',
    year: 1982, category: 'monitor',
    spec: 16,
    specLabel: '16 on-screen colors',
    speech: 'number of colors on screen',
    factoid: 'ColecoVision\'s TMS9928A chip displayed 16 colors and near-arcade-quality graphics — it was the console to beat in 1982!',
    imageUrl: WC('ColecoVision-Console-Set.jpg'),
  },
  {
    id: 'apple2_locolor',
    name: 'Apple II Lo-Res Mode',
    year: 1977, category: 'monitor',
    spec: 16,
    specLabel: '16 colors',
    speech: 'number of colors in low-resolution mode',
    factoid: 'Apple II\'s Lo-Res mode offered 16 colors on a 40×48 grid. Small blocks, big dreams — it launched a million bedroom programmers!',
    imageUrl: WC('Apple_II_Plus.jpg'),
  },
  {
    id: 'gbc_colors_onscreen',
    name: 'Game Boy Color',
    year: 1998, category: 'monitor',
    spec: 56,
    specLabel: '56 colors on screen',
    speech: 'number of colors displayable at once',
    factoid: 'The Game Boy Color could display up to 56 colors simultaneously — a huge leap from the original\'s 4 shades of green!',
    imageUrl: WC('Game-Boy-Color-Purple.jpg'),
  },
  {
    id: 'n64_controller_buttons',
    name: 'Nintendo 64 Controller',
    year: 1996, category: 'computer',
    spec: 14,
    specLabel: '14 buttons',
    speech: 'number of buttons',
    factoid: 'The N64\'s wild three-pronged controller had 14 buttons including 4 C-buttons and the first mainstream analog stick — it changed how we play 3D games!',
    imageUrl: WC('N64-Controller-Gray.jpg'),
  },
  {
    id: 'nes_sprites_max',
    name: 'NES Sprite Memory',
    year: 1983, category: 'chip',
    spec: 64,
    specLabel: '64 hardware sprites',
    speech: 'number of hardware sprites',
    factoid: 'The NES PPU could store 64 sprites total but only show 8 per scanline — clever programmers flicked sprites rapidly to fake more enemies on screen!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'genesis_sprites',
    name: 'Sega Genesis VDP',
    year: 1988, category: 'chip',
    spec: 80,
    specLabel: '80 hardware sprites',
    speech: 'number of hardware sprites',
    factoid: 'The Sega Genesis VDP could handle 80 sprites — more than the NES and SNES — giving Sonic\'s world its fast-scrolling, enemy-packed chaos!',
    imageUrl: WC('Sega-Genesis-Mk1-Console-Set.jpg'),
  },
  {
    id: 'jaguar_controller_buttons',
    name: 'Atari Jaguar Controller',
    year: 1993, category: 'computer',
    spec: 17,
    specLabel: '17 buttons',
    speech: 'number of buttons',
    factoid: 'The Atari Jaguar\'s controller had 17 buttons including a numeric keypad — great for strategy games, overwhelming for action games!',
    imageUrl: WC('Atari-Jaguar-Controller.jpg'),
  },

  // ── HUNDREDS (new) ────────────────────────────────────────
  {
    id: 'odyssey2_ram',
    name: 'Magnavox Odyssey²',
    year: 1978, category: 'computer',
    spec: 192,
    specLabel: '192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Odyssey² squeezed 192 bytes of RAM into a console that could still do voice synthesis with a special add-on cartridge!',
    imageUrl: WC('Magnavox-Odyssey2-Console-Set.jpg'),
  },
  {
    id: 'atari800_colors',
    name: 'Atari 400/800 CTIA',
    year: 1979, category: 'monitor',
    spec: 128,
    specLabel: '128 simultaneous colors',
    speech: 'number of colors displayable at once',
    factoid: 'The Atari 400/800\'s CTIA chip could display 128 colors simultaneously — far more than any competitor in 1979, making its graphics jaw-dropping!',
    imageUrl: WC('Atari-400-Computer-FL.jpg'),
  },
  {
    id: 'pce_palette',
    name: 'TurboGrafx-16',
    year: 1987, category: 'monitor',
    spec: 512,
    specLabel: '512 color palette',
    speech: 'total number of colors in the palette',
    factoid: 'The TurboGrafx-16\'s 512-color palette and 482-color on-screen capability made it look stunning — NEC\'s secret weapon in the 16-bit wars!',
    imageUrl: WC('PCEngine-Console-001.jpg'),
  },
  {
    id: 'apple2_hires_width',
    name: 'Apple II Hi-Res Mode',
    year: 1977, category: 'monitor',
    spec: 280,
    specLabel: '280 px screen width',
    speech: 'screen width in pixels',
    factoid: 'Apple II\'s Hi-Res mode offered 280 pixel columns — still only 6 colors, but enough to draw crisp graphics that made the computer feel like magic!',
    imageUrl: WC('Apple_II_Plus.jpg'),
  },
  {
    id: 'snes_sprites',
    name: 'SNES Sprite Engine',
    year: 1990, category: 'chip',
    spec: 128,
    specLabel: '128 hardware sprites',
    speech: 'number of hardware sprites',
    factoid: 'The SNES could handle 128 sprites at once — that\'s why Super Mario World could pack enemies, power-ups, and fireworks on screen simultaneously!',
    imageUrl: WC('SNES-Mod1-Console-Set.jpg'),
  },
  {
    id: 'nes_screen_height',
    name: 'NES Display',
    year: 1983, category: 'monitor',
    spec: 240,
    specLabel: '240 px screen height',
    speech: 'screen height in pixels',
    factoid: 'The NES drew 240 scanlines per frame. Programmers often changed the palette mid-scanline, creating the illusion of more colors than existed!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'ti994a_ram',
    name: 'TI-99/4A',
    year: 1979, category: 'computer',
    spec: 256,
    specLabel: '256 bytes scratchpad RAM',
    speech: 'number of bytes of scratchpad RAM',
    factoid: 'The TI-99/4A\'s CPU could only directly use 256 bytes of fast scratchpad RAM — all other memory required tricky bank-switching to reach!',
    imageUrl: WC('TI-99-4A-Computer.jpg'),
  },
  {
    id: 'rca_studio2',
    name: 'RCA Studio II',
    year: 1977, category: 'computer',
    spec: 512,
    specLabel: '512 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The RCA Studio II was one of the first consoles with built-in games — and fit them all into just 512 bytes of RAM, with no joysticks (just keypads)!',
    imageUrl: WC('RCA-Studio-II.jpg'),
  },

  // ── THOUSANDS (new) ──────────────────────────────────────
  {
    id: 'intel8008',
    name: 'Intel 8008 CPU',
    year: 1972, category: 'chip',
    spec: 3500,
    specLabel: '3,500 transistors',
    speech: 'number of transistors',
    factoid: 'The Intel 8008 was the world\'s first 8-bit microprocessor — originally designed for a smart terminal, it launched the era of general-purpose computing!',
    imageUrl: WC('Intel_C8008.jpg'),
  },
  {
    id: 'intel8080',
    name: 'Intel 8080 CPU',
    year: 1974, category: 'chip',
    spec: 6000,
    specLabel: '6,000 transistors',
    speech: 'number of transistors',
    factoid: 'The Intel 8080 powered the Altair 8800 — the machine that inspired Bill Gates and Paul Allen to write BASIC and found Microsoft!',
    imageUrl: WC('KL_Intel_C8080A.jpg'),
  },
  {
    id: 'colecovision_ram',
    name: 'ColecoVision RAM',
    year: 1982, category: 'computer',
    spec: 1024,
    specLabel: '1,024 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'ColecoVision had just 1 KB of RAM but delivered near-arcade-quality games. The trick? Streaming data straight from ROM with minimal buffering!',
    imageUrl: WC('ColecoVision-Console-Set.jpg'),
  },
  {
    id: 'vic20_ram',
    name: 'Commodore VIC-20',
    year: 1980, category: 'computer',
    spec: 3583,
    specLabel: '3,583 bytes free RAM',
    speech: 'number of bytes of free user RAM',
    factoid: 'The VIC-20 had only 3,583 bytes free for BASIC programs — yet it was the first computer to sell a million units and inspired countless young programmers!',
    imageUrl: WC('Commodore-VIC-20-FL.jpg'),
  },
  {
    id: 'bally_astrocade_ram',
    name: 'Bally Astrocade',
    year: 1978, category: 'computer',
    spec: 4096,
    specLabel: '4,096 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Bally Astrocade was originally sold only in arcades before going home. Its 4 KB of RAM and custom graphics chip produced surprisingly lush visuals!',
    imageUrl: WC('Bally-Astrocade-Console-Set.jpg'),
  },
  {
    id: 'atari7800_ram',
    name: 'Atari 7800',
    year: 1984, category: 'computer',
    spec: 4096,
    specLabel: '4,096 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Atari 7800 played both 7800 and 2600 cartridges — backward compatibility in 1984! Its 4 KB of RAM enabled arcade-perfect ports of Joust and Dig Dug.',
    imageUrl: WC('Atari-7800-Console.jpg'),
  },
  {
    id: 'sega_sg1000_ram',
    name: 'Sega SG-1000',
    year: 1983, category: 'computer',
    spec: 1024,
    specLabel: '1,024 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The SG-1000 launched in Japan on the very same day as the Famicom! Sega\'s first console managed 1 KB of RAM and launched a hardware empire.',
    imageUrl: WC('Sega-SG-1000-Console-Set.jpg'),
  },
  {
    id: 'msx_ram',
    name: 'MSX Computer',
    year: 1983, category: 'computer',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'MSX was a universal standard backed by Microsoft and ASCII — any MSX cartridge worked on any MSX computer, whether made by Sony, Panasonic, or Casio!',
    imageUrl: WC('MSX_computer.jpg'),
  },
  {
    id: 'game_gear_palette',
    name: 'Sega Game Gear',
    year: 1990, category: 'monitor',
    spec: 4096,
    specLabel: '4,096 color palette',
    speech: 'total number of colors in the palette',
    factoid: 'The Sega Game Gear\'s 4,096-color palette matched the Mega Drive — but it drained 6 AA batteries in about 3 hours, much to parents\' dismay!',
    imageUrl: WC('Sega-Game-Gear-Mk1.jpg'),
  },

  // ── TEN-THOUSANDS (new) ───────────────────────────────────
  {
    id: 'apple2e_ram',
    name: 'Apple IIe',
    year: 1983, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Apple IIe dominated classrooms worldwide with 64 KB of RAM. It stayed in Apple\'s product lineup until 1993 — a decade-long run!',
    imageUrl: WC('Apple-IIe-Computer.jpg'),
  },
  {
    id: 'snes_color_palette',
    name: 'SNES Color Palette',
    year: 1990, category: 'monitor',
    spec: 32768,
    specLabel: '32,768 color palette',
    speech: 'total number of colors in the palette',
    factoid: 'The SNES could pick from 32,768 possible colors — and with Mode 7\'s rotation and scaling tricks, it made 2D games look almost three-dimensional!',
    imageUrl: WC('SNES-Mod1-Console-Set.jpg'),
  },
  {
    id: 'genesis_vram_64k',
    name: 'Sega Genesis Video RAM',
    year: 1988, category: 'chip',
    spec: 65536,
    specLabel: '65,536 bytes video RAM',
    speech: 'number of bytes of video RAM',
    factoid: 'The Sega Genesis VDP had 64 KB of video RAM — enough to store all the tiles, sprites, and scrolling layers that made Sonic the Hedgehog dazzle!',
    imageUrl: WC('Sega-Genesis-Mk1-Console-Set.jpg'),
  },
  {
    id: 'zxspectrum16k',
    name: 'ZX Spectrum 16K',
    year: 1982, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The budget ZX Spectrum 16K launched at £125 in 1982. Many kids begged for the 48K model — three times the memory for just 25% more in price!',
    imageUrl: WC('ZXSpectrum48k.jpg'),
  },
  {
    id: 'bbc_micro_b',
    name: 'BBC Micro Model B',
    year: 1981, category: 'computer',
    spec: 32768,
    specLabel: '32,768 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The BBC Micro was part of a BBC Computer Literacy Project that put it into British schools. It taught an entire generation — including the founders of ARM!',
    imageUrl: WC('BBC_Micro_Front_Restored.jpg'),
  },
  {
    id: 'atari_lynx_ram',
    name: 'Atari Lynx',
    year: 1989, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Atari Lynx was the world\'s first handheld with a color LCD screen! Its 64 KB of RAM powered graphics that left the Game Boy in the dust.',
    imageUrl: WC('Atari-Lynx-Mk2.jpg'),
  },
  {
    id: 'zilog_z8000',
    name: 'Zilog Z8000 CPU',
    year: 1979, category: 'chip',
    spec: 17500,
    specLabel: '17,500 transistors',
    speech: 'number of transistors',
    factoid: 'The Zilog Z8000 was a high-end 16-bit rival to the 8086. It powered early Unix workstations and showed what 17,500 transistors were capable of!',
    imageUrl: WC('Zilog-Z8000.jpg'),
  },
  {
    id: 'dragon32_ram',
    name: 'Dragon 32',
    year: 1982, category: 'computer',
    spec: 32768,
    specLabel: '32,768 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The British-built Dragon 32 ran Microsoft BASIC and packed 32 KB into an affordable home computer — despite its quality, it was outsold by the ZX Spectrum!',
    imageUrl: WC('Dragon_32_Front.jpg'),
  },

  // ── HUNDRED-THOUSANDS (new) ───────────────────────────────
  {
    id: 'amstrad_cpc6128',
    name: 'Amstrad CPC 6128',
    year: 1985, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Amstrad CPC 6128 came with a built-in 3-inch floppy drive and 128 KB of RAM — it dominated UK computing charts in the mid-1980s!',
    imageUrl: WC('Amstrad_CPC6128.jpg'),
  },
  {
    id: 'apple_iigs_ram',
    name: 'Apple IIGS',
    year: 1986, category: 'computer',
    spec: 262144,
    specLabel: '262,144 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Apple secretly capped the IIGS\'s speed to prevent it from outselling the Mac. Its 256 KB of RAM still powered stunning 16-bit graphics and sound!',
    imageUrl: WC('Apple-IIgs-ROM3.jpg'),
  },
  {
    id: 'motorola68020',
    name: 'Motorola 68020 CPU',
    year: 1984, category: 'chip',
    spec: 200000,
    specLabel: '200,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 68020 brought full 32-bit computing to workstations. Its 200,000 transistors powered the Mac II and early Sun workstations in 1984!',
    imageUrl: WC('KL_Motorola_68020.jpg'),
  },
  {
    id: 'snes_main_ram',
    name: 'Super Nintendo RAM',
    year: 1990, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The SNES\'s 128 KB of RAM stored game states, AI, music, and physics data — yet delivered some of the most complex 16-bit experiences ever made!',
    imageUrl: WC('SNES-Mod1-Console-Set.jpg'),
  },
  {
    id: 'floppy_360k',
    name: '5.25" Floppy Disk',
    year: 1982, category: 'cartridge',
    spec: 368640,
    specLabel: '368,640 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'The 360 KB double-density floppy was the IBM PC\'s standard medium — entire operating systems, word processors, and games shipped on one floppy disk!',
    imageUrl: WC('5.25_inch_floppy_discs.jpg'),
  },
  {
    id: 'amiga1000_rom',
    name: 'Amiga 1000 Kickstart',
    year: 1985, category: 'cartridge',
    spec: 262144,
    specLabel: '262,144 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'The Amiga 1000 loaded its entire operating system from a special 256 KB ROM cartridge inserted at boot — a quirky ritual that defined early Amiga culture!',
    imageUrl: WC('Amiga_1000DP.jpg'),
  },
  {
    id: 'ibm_pcat_ram',
    name: 'IBM PC AT',
    year: 1984, category: 'computer',
    spec: 262144,
    specLabel: '262,144 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The IBM PC AT came standard with 256 KB of RAM and an 80286 CPU. It set the corporate computing standard for the entire second half of the 1980s!',
    imageUrl: WC('IBM_PC_AT.jpg'),
  },
  {
    id: 'floppy_720k',
    name: '3.5" Floppy Disk (DD)',
    year: 1984, category: 'cartridge',
    spec: 737280,
    specLabel: '737,280 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'The 3.5-inch double-density floppy held 720 KB in a hard plastic shell — twice the data of its 5.25-inch predecessor, and it survived being sat on!',
    imageUrl: WC('Floppy_disk_2009_G1.jpg'),
  },

  // ─── MILLIONS (1,000,000+) ────────────────────────────────
  {
    id: 'mac_plus',
    name: 'Macintosh Plus',
    year: 1986, category: 'computer',
    spec: 1048576,
    specLabel: '1,048,576 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: '1,048,576 bytes = exactly 1 megabyte. The Mac Plus was the first truly useful Mac!',
    imageUrl: WC('Macintosh_Plus.jpg'),
  },
  {
    id: 'intel486',
    name: 'Intel 486 CPU',
    year: 1989, category: 'chip',
    spec: 1200000,
    specLabel: '1,200,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 486 was so fast it ran DOOM — the game that changed everything.',
    imageUrl: WC('Intel486DX2chip.jpg'),
  },
  {
    id: 'donkeykong_wr',
    name: 'Donkey Kong Cabinet',
    year: 1981, category: 'arcade',
    spec: 1272700,
    specLabel: '1,272,700 world record',
    speech: 'all-time world record score',
    factoid: 'The Donkey Kong world record battle was documented in "The King of Kong" (2007)!',
    imageUrl: WC('Donkey_Kong_arcade_game.jpg'),
  },
  {
    id: 'sxga_monitor',
    name: 'SXGA Monitor (1280×1024)',
    year: 1996, category: 'monitor',
    spec: 1310720,
    specLabel: '1,310,720 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'SXGA\'s 1280×1024 resolution (1.3 megapixels) was the first "high-res" standard for desktops.',
    imageUrl: WC('Dell_1901FP_monitor.jpg'),
  },
  {
    id: 'pacman_perfect',
    name: 'Pac-Man Cabinet',
    year: 1980, category: 'arcade',
    spec: 3333360,
    specLabel: '3,333,360 perfect score',
    speech: 'perfect game score',
    factoid: 'A "perfect" Pac-Man means eating every dot, energizer, ghost, and fruit on all 256 levels!',
    imageUrl: WC('Pac-man_arcade_game.jpg'),
  },
  {
    id: 'genesis_vram',
    name: 'Sega Genesis / Mega Drive',
    year: 1988, category: 'computer',
    spec: 1048576,
    specLabel: '1,048,576 bytes RAM',
    speech: 'total number of bytes of RAM',
    factoid: 'Sega dared players to "do what Nintendon\'t" — and the Genesis had a full megabyte of RAM!',
    imageUrl: WC('Sega-Genesis-Mk1-Console-Set.jpg'),
  },
  {
    id: 'intel_pentium',
    name: 'Intel Pentium CPU',
    year: 1993, category: 'chip',
    spec: 3100000,
    specLabel: '3,100,000 transistors',
    speech: 'number of transistors',
    factoid: 'The Pentium had 3.1 million transistors — and became the chip that defined the 1990s PC.',
    imageUrl: WC('KL_Intel_Pentium_A80501.jpg'),
  },
  {
    id: 'playstation1_ram',
    name: 'PlayStation 1',
    year: 1994, category: 'computer',
    spec: 2097152,
    specLabel: '2,097,152 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'With 2 MB of RAM and a 33 MHz MIPS CPU, the PlayStation 1 brought 3D polygonal graphics to a mass audience for the very first time!',
    imageUrl: WC('PlayStation-SCPH-1000.jpg'),
  },
  {
    id: 'n64_ram',
    name: 'Nintendo 64',
    year: 1996, category: 'computer',
    spec: 4194304,
    specLabel: '4,194,304 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The N64 packed 4 MB of blazing-fast RDRAM — revolutionary but expensive. The cost forced Nintendo to stick with cartridges instead of CDs!',
    imageUrl: WC('Nintendo-64-Console-Set.jpg'),
  },
  {
    id: 'pentium_pro',
    name: 'Intel Pentium Pro',
    year: 1995, category: 'chip',
    spec: 5500000,
    specLabel: '5,500,000 transistors',
    speech: 'number of transistors',
    factoid: 'The Pentium Pro was the first chip with an on-die L2 cache. Its 5.5 million transistors powered early web servers and engineering workstations!',
    imageUrl: WC('Intel_Pentium_Pro.jpg'),
  },
  {
    id: 'threedO_ram',
    name: '3DO Interactive',
    year: 1993, category: 'computer',
    spec: 2097152,
    specLabel: '2,097,152 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The 3DO launched at $699 in 1993 — more than many TVs at the time! Its 2 MB of RAM and CD-ROM drive promised the future of gaming.',
    imageUrl: WC('3DO-FZ-1-Cropped.jpg'),
  },
  {
    id: 'mario64_cart',
    name: 'Super Mario 64 Cart',
    year: 1996, category: 'cartridge',
    spec: 8388608,
    specLabel: '8,388,608 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Super Mario 64 shipped on a 64-megabit (8 MB) cartridge — the largest N64 cart at launch! It introduced true 3D platforming and redefined video games.',
    imageUrl: WC('Nintendo-64-Console-Set.jpg'),
  },

  // ═══════════════════════════════════════════════════════════
  // BATCH 3 — RESEARCH TEAM (9 AGENTS)
  // ═══════════════════════════════════════════════════════════

  // ── CPU CHIPS ────────────────────────────────────────────────
  {
    id: 'am2901',
    name: 'AMD Am2901',
    year: 1975, category: 'chip',
    spec: 540,
    specLabel: '~540 logic gates',
    speech: 'number of logic gates',
    factoid: 'AMD\'s Am2901 was a 4-bit "bit-slice" chip — you stacked multiples to build any word size you wanted. It powered Battlezone arcade boards and F-16 fighter jet computers!',
    imageUrl: WC('Ic-photo-AMD--Am2901.jpg'),
  },
  {
    id: 'motorola_6800',
    name: 'Motorola 6800',
    year: 1974, category: 'chip',
    spec: 4100,
    specLabel: '4,100 transistors',
    speech: 'number of transistors',
    factoid: 'Every one of the 6800\'s 4,100 transistors was drawn by hand. A rival to the 6502, it became the heart of early home computers and medical monitoring devices.',
    imageUrl: WC('Motorola_6800_die.jpg'),
  },
  {
    id: 'intel_8085',
    name: 'Intel 8085',
    year: 1976, category: 'chip',
    spec: 6500,
    specLabel: '6,500 transistors',
    speech: 'number of transistors',
    factoid: 'The 8085 added a built-in clock and serial port so it needed no external support chips — all in 6,500 transistors. It was the CPU inside the first portable medical monitors.',
    imageUrl: WC('Intel_8085A_die.jpg'),
  },
  {
    id: 'arm2',
    name: 'ARM2 CPU',
    year: 1986, category: 'chip',
    spec: 30000,
    specLabel: '30,000 transistors',
    speech: 'number of transistors',
    factoid: 'The ARM2 had only 30,000 transistors yet outperformed the Intel 286. It debuted in the Acorn Archimedes and laid the foundation for every smartphone CPU in existence today.',
    imageUrl: WC('ARM_Acorn_RISC_Machine.jpg'),
  },
  {
    id: 'arm6',
    name: 'ARM6 CPU',
    year: 1991, category: 'chip',
    spec: 35000,
    specLabel: '35,000 transistors',
    speech: 'number of transistors',
    factoid: 'At 35,000 transistors, the ARM6 powered Apple\'s Newton PDA and ran on tiny batteries — setting the stage for the mobile revolution that would reshape the world.',
    imageUrl: WC('GPS_ARM610_die.JPG'),
  },
  {
    id: 'nec_v20',
    name: 'NEC V20',
    year: 1982, category: 'chip',
    spec: 63000,
    specLabel: '63,000 transistors',
    speech: 'number of transistors',
    factoid: 'NEC\'s V20 was a drop-in replacement for Intel\'s 8088 that ran 30% faster. Its 63,000 transistors also let it execute 8080 code natively — a trick Intel never bothered with.',
    imageUrl: WC('NEC_V20_CPU_chip.jpg'),
  },
  {
    id: 'motorola_68010',
    name: 'Motorola 68010',
    year: 1982, category: 'chip',
    spec: 69000,
    specLabel: '69,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 68010 added virtual memory support in one revision, making it the CPU of choice for early Unix workstations. Sun Microsystems bet their entire company on it.',
    imageUrl: WC('KL_Motorola_MC68010.jpg'),
  },
  {
    id: 'mips_r3000',
    name: 'MIPS R3000',
    year: 1988, category: 'chip',
    spec: 115000,
    specLabel: '115,000 transistors',
    speech: 'number of transistors',
    factoid: 'Sony dropped the R3000 into the PlayStation at 33 MHz — 115,000 transistors driving millions of polygon-pushing 3D games and launching the modern console era.',
    imageUrl: WC('MIPS_R3000A_die.JPG'),
  },
  {
    id: 'motorola_68030',
    name: 'Motorola 68030',
    year: 1987, category: 'chip',
    spec: 273000,
    specLabel: '273,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 68030 powered the Mac IIx and early NeXT workstations. Its on-chip MMU let programmers run real virtual memory for the first time on a desktop machine.',
    imageUrl: WC('KL_Motorola_MC68030.jpg'),
  },
  {
    id: 'motorola_68040',
    name: 'Motorola 68040',
    year: 1990, category: 'chip',
    spec: 1200000,
    specLabel: '1,200,000 transistors',
    speech: 'number of transistors',
    factoid: 'The 68040 had an FPU, MMU, and dual 4K caches on one die — 1.2 million transistors at 40 MHz. Tim Berners-Lee used a NeXTstation with this chip to invent the World Wide Web.',
    imageUrl: WC('KL_Motorola_MC68040.jpg'),
  },
  {
    id: 'intel_dx4',
    name: 'Intel 486 DX4',
    year: 1994, category: 'chip',
    spec: 1600000,
    specLabel: '1,600,000 transistors',
    speech: 'number of transistors',
    factoid: 'The DX4 tripled its external clock to hit 100 MHz — Intel\'s last hurrah for the 486 line. Its 1.6 million transistors bridged the performance gap until the Pentium took over.',
    imageUrl: WC('Intel_80486DX4_&EW_die.JPG'),
  },
  {
    id: 'amd_k5',
    name: 'AMD K5',
    year: 1996, category: 'chip',
    spec: 4300000,
    specLabel: '4,300,000 transistors',
    speech: 'number of transistors',
    factoid: 'AMD\'s first fully in-house CPU used RISC micro-ops internally to decode x86 instructions — a clever trick that every modern CPU, from Intel to Apple Silicon, still uses today.',
    imageUrl: WC('AMD_K5_die.JPG'),
  },

  // ── US HOME COMPUTERS ────────────────────────────────────────
  {
    id: 'apple2_orig',
    name: 'Apple II (Original)',
    year: 1977, category: 'computer',
    spec: 4096,
    specLabel: '4,096 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The original Apple II launched with just 4 KB of RAM — but its open expansion slots let hobbyists add more memory and invent entirely new categories of software like VisiCalc!',
    imageUrl: WC('Apple_II_IMG_4212.jpg'),
  },
  {
    id: 'apple2_plus',
    name: 'Apple II Plus',
    year: 1979, category: 'computer',
    spec: 49152,
    specLabel: '49,152 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Apple II Plus shipped with 48 KB of RAM — the sweet spot for running VisiCalc, the world\'s first spreadsheet, which single-handedly turned the Apple II into a business machine.',
    imageUrl: WC('Apple_II_Plus.jpg'),
  },
  {
    id: 'apple3',
    name: 'Apple III',
    year: 1980, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Apple\'s first business computer shipped with 128 KB — but a design flaw caused chips to pop out of their sockets, forcing a recall of all 14,000 first-run units!',
    imageUrl: WC('Apple_III.jpg'),
  },
  {
    id: 'apple_lisa',
    name: 'Apple Lisa',
    year: 1983, category: 'computer',
    spec: 1048576,
    specLabel: '1,048,576 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Lisa was the first mass-market PC with a GUI and mouse, packing 1 MB of RAM when competitors had 64 KB. At $9,995 — over $30,000 today — it nearly bankrupted Apple.',
    imageUrl: WC('Apple_Lisa_(6932887589).jpg'),
  },
  {
    id: 'pet2001',
    name: 'Commodore PET 2001',
    year: 1977, category: 'computer',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The PET was one of the "1977 Trinity" alongside the Apple II and TRS-80. Its 8 KB model came with a built-in tape deck, monitor, and keyboard all in one box for $795!',
    imageUrl: WC('Commodore_2001_Series-IMG_0448b.jpg'),
  },
  {
    id: 'commodore128',
    name: 'Commodore 128',
    year: 1985, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The C128 crammed three computers in one: C64-compatible mode, a native 128 KB mode, and CP/M mode — yet 80% of owners used it only in C64 mode, ignoring all that extra RAM!',
    imageUrl: WC('Commodore128.jpg'),
  },
  {
    id: 'plus4',
    name: 'Commodore Plus/4',
    year: 1984, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Designed to replace the C64, the Plus/4 had 64 KB of RAM and four built-in productivity apps — but its C64 incompatibility made it a flop despite solid technical specs.',
    imageUrl: WC('Commodore_Plus_4.jpg'),
  },
  {
    id: 'coco1',
    name: 'TRS-80 Color Computer',
    year: 1980, category: 'computer',
    spec: 4096,
    specLabel: '4,096 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The CoCo\'s Motorola 6809 was the most powerful 8-bit CPU in any home computer — yet Radio Shack launched the 4 KB base model at just $399, cheap enough for millions of families.',
    imageUrl: WC('TRS-80_Color_Computer_1.jpg'),
  },
  {
    id: 'trs80_model1',
    name: 'TRS-80 Model I',
    year: 1977, category: 'computer',
    spec: 4096,
    specLabel: '4,096 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Radio Shack sold 10,000 TRS-80 Model I computers in the first month — shocking everyone, including Radio Shack. Its 4 KB of RAM was just enough to run BASIC and the games sold in stores!',
    imageUrl: WC('Radio_Shack_Tandy_TRS-80_Model_I_System.JPG'),
  },
  {
    id: 'trs80_model4',
    name: 'TRS-80 Model 4',
    year: 1983, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The TRS-80 Model 4 ran at 4 MHz with 64 KB of RAM and an 80-column display. It finally let Radio Shack\'s flagship computer run serious CP/M business software.',
    imageUrl: WC('RadioShack_TRS-80_mod4-IMG_5778.jpg'),
  },
  {
    id: 'ibm_pc_5150',
    name: 'IBM PC 5150',
    year: 1981, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The original IBM PC launched with just 16 KB of RAM. IBM\'s open architecture — chosen to save development time — accidentally created the entire PC-compatible industry.',
    imageUrl: WC('IBM_PC_5150.jpg'),
  },
  {
    id: 'tandy1000',
    name: 'Tandy 1000',
    year: 1984, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Tandy 1000 was a better PCjr than the PCjr — with 128 KB RAM, 16-color graphics, and 3-voice sound. It became the de-facto standard for PC gaming in the late 1980s!',
    imageUrl: WC('Tandy_1000_computer_original.jpg'),
  },
  {
    id: 'kaypro2',
    name: 'Kaypro II',
    year: 1982, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Kaypro packed a Z80 CPU, 64 KB RAM, a bright 9-inch green screen, and two floppy drives into a 26-pound "luggable" metal case — and bundled $1,000 of software for just $1,595!',
    imageUrl: WC('Kaypro_II.jpg'),
  },
  {
    id: 'osborne1',
    name: 'Osborne 1',
    year: 1981, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The world\'s first mass-produced portable computer weighed 24.5 pounds with a 5-inch screen. Its 64 KB of RAM and bundled software sold 10,000 units a month at peak!',
    imageUrl: WC('Osborne-1_Portable_Computer.jpg'),
  },
  {
    id: 'next_cube',
    name: 'NeXT Computer Cube',
    year: 1988, category: 'computer',
    spec: 8388608,
    specLabel: '8,388,608 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Steve Jobs\' NeXT Cube had 8 MB of RAM in a perfect 1-foot magnesium cube. It was used to write the world\'s first web browser — and to develop DOOM and Quake.',
    imageUrl: WC('NeXTcube_motherboard.jpg'),
  },

  // ── UK / EUROPEAN COMPUTERS ──────────────────────────────────
  {
    id: 'zx80',
    name: 'Sinclair ZX80',
    year: 1980, category: 'computer',
    spec: 1024,
    specLabel: '1,024 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The first home computer to sell for under £100, the ZX80 blanked the TV screen every time it ran a program — the CPU was too busy calculating to draw the picture!',
    imageUrl: WC('ZX80.jpg'),
  },
  {
    id: 'zx81',
    name: 'Sinclair ZX81',
    year: 1981, category: 'computer',
    spec: 1024,
    specLabel: '1,024 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Sinclair shrunk the ZX80 from 21 chips down to just 4. A single custom Ferranti ULA replaced 18 of them — over 1.5 million ZX81s were sold worldwide.',
    imageUrl: WC('Sinclair_ZX81.jpg'),
  },
  {
    id: 'jupiter_ace',
    name: 'Jupiter Ace',
    year: 1982, category: 'computer',
    spec: 3072,
    specLabel: '3,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Jupiter Ace used FORTH instead of BASIC, making it up to 10× faster than comparable machines — but only about 5,000 were ever sold before the company folded.',
    imageUrl: WC('Jupiter_ACE_(restored).JPG'),
  },
  {
    id: 'oric1_16k',
    name: 'Oric-1 16K',
    year: 1983, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Oric-1 was the top-selling home computer in France in 1983, with about 50,000 sold there — and 160,000 more in the UK — for a computer barely anyone remembers today.',
    imageUrl: WC('Oric-1_avec_logo_couleur.jpg'),
  },
  {
    id: 'acorn_electron',
    name: 'Acorn Electron',
    year: 1983, category: 'computer',
    spec: 32768,
    specLabel: '32,768 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Acorn designed the Electron as a budget BBC Micro, reducing 102 chips to just 14. Demand was so massive at Christmas 1983 that 300,000 orders came in but only 30,000 could ship!',
    imageUrl: WC('Acorn_Electron_2.jpg'),
  },
  {
    id: 'cpc464',
    name: 'Amstrad CPC 464',
    year: 1984, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The CPC 464 came with a built-in cassette deck and monitor — no extras needed. It became one of the best-selling UK home computers of the mid-1980s.',
    imageUrl: WC('Amstrad_CPC_464_(1984)_2.jpg'),
  },
  {
    id: 'dragon64',
    name: 'Dragon 64',
    year: 1983, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Dragon 64 doubled its predecessor\'s RAM and added RS-232 serial — the most capable Dragon ever built. It was partly compatible with the American TRS-80 Color Computer!',
    imageUrl: WC('Dragon_64.jpg'),
  },
  {
    id: 'tatung_einstein',
    name: 'Tatung Einstein TC-01',
    year: 1984, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Designed in Bradford, built in Telford, the Einstein starred in the 1985 film Weird Science — it was the computer used to conjure a wish-granting woman out of thin air!',
    imageUrl: WC('Tatung_Einstein_Computer.jpg'),
  },
  {
    id: 'memotech_mtx512',
    name: 'Memotech MTX512',
    year: 1983, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The premium aluminium MTX512 nearly landed a deal to supply 64,000 Soviet schools — but the USSR chose Yamaha MSX machines instead. A bizarre footnote in Cold War tech history!',
    imageUrl: WC('Memotech_MTX512.jpg'),
  },
  {
    id: 'camputers_lynx_96',
    name: 'Camputers Lynx 96K',
    year: 1983, category: 'computer',
    spec: 98304,
    specLabel: '98,304 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Camputers Lynx always ran in high-resolution 256×252 color graphics — unusual for a home computer. Only 30,000 were sold before production ended in 1984.',
    imageUrl: WC('Camputers_Lynx_48k_(white_background).jpg'),
  },
  {
    id: 'zxspectrum128',
    name: 'ZX Spectrum 128K',
    year: 1985, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The 128K launched first in Spain in 1985, then came to the UK in 1986 with a built-in 3-channel AY sound chip that transformed Spectrum music forever.',
    imageUrl: WC('ZX_Spectrum128K.jpg'),
  },
  {
    id: 'bbc_master128',
    name: 'BBC Master 128',
    year: 1986, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The BBC Master had a built-in real-time clock and 128 KB of RAM. It powered the BBC\'s legendary 1986 Domesday Project — a national interactive videodisc archive of Britain.',
    imageUrl: WC('Acorn_BBC_Master_Series_Microcomputer.jpg'),
  },
  {
    id: 'amstrad_pcw8256',
    name: 'Amstrad PCW 8256',
    year: 1985, category: 'computer',
    spec: 262144,
    specLabel: '262,144 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Codenamed "Joyce" after Alan Sugar\'s secretary, the PCW cost less than a quarter of a comparable PC and came bundled with a printer — making word processing affordable for ordinary homes.',
    imageUrl: WC('Schneider-Joyce-PCW-8256--Museum-Enter-6094720.jpg'),
  },
  {
    id: 'sam_coupe',
    name: 'SAM Coupé',
    year: 1989, category: 'computer',
    spec: 262144,
    specLabel: '262,144 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Founded by two ex-Sinclair engineers, the SAM was designed as the ZX Spectrum\'s true 32-bit successor — but only about 12,000 units sold before the company went into receivership.',
    imageUrl: WC('SAM_Coupe.jpg'),
  },

  // ── JAPANESE COMPUTERS ───────────────────────────────────────
  {
    id: 'epoch_scv',
    name: 'Epoch Super Cassette Vision',
    year: 1984, category: 'computer',
    spec: 128,
    specLabel: '128 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Super Cassette Vision matched the Atari 2600\'s tiny 128-byte RAM yet its NEC µPD7801 CPU outpaced it in raw speed — fitting more power into the same amount of memory!',
    imageUrl: WC('Super-Cassette-Vision-wController-R.jpg'),
  },
  {
    id: 'casio_pv1000',
    name: 'Casio PV-1000',
    year: 1983, category: 'computer',
    spec: 2048,
    specLabel: '2,048 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Casio tried to enter the console market with the PV-1000, but its 2 KB of RAM and weak game library couldn\'t compete with the Famicom that launched the same year.',
    imageUrl: WC('Casio-PV1000-Console-Set.jpg'),
  },
  {
    id: 'bandai_sv8000',
    name: 'Bandai Super Vision 8000',
    year: 1979, category: 'computer',
    spec: 1024,
    specLabel: '1,024 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Bandai\'s Super Vision 8000 squeezed an entire game library onto cartridges because the console itself had only 1 KB of working RAM — every byte had to count!',
    imageUrl: WC('Bandaisupervisionconsole.jpg'),
  },
  {
    id: 'nec_pc6001',
    name: 'NEC PC-6001',
    year: 1981, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'NEC\'s budget PC-6001 was nicknamed the "Pasokon Mini" and introduced a generation of Japanese kids to home computing — with 16 KB of RAM and a cheerful voice synthesis chip.',
    imageUrl: WC('NEC_PC-6001.jpg'),
  },
  {
    id: 'nec_pc8001',
    name: 'NEC PC-8001',
    year: 1979, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The PC-8001 launched Japan\'s personal computer revolution in 1979. Its 16 KB of RAM felt enormous compared to microcontrollers of the era.',
    imageUrl: WC('Early_Japanese_personal_computers_NEC_PC-8001.jpg'),
  },
  {
    id: 'sharp_mz80k',
    name: 'Sharp MZ-80K',
    year: 1978, category: 'computer',
    spec: 49152,
    specLabel: '49,152 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The MZ-80K was a "clean machine" — it had no built-in BASIC, so users had to load their own software from tape before doing absolutely anything at all.',
    imageUrl: WC('Sharp_MZ-80K_computer.jpg'),
  },
  {
    id: 'nec_pc8801',
    name: 'NEC PC-8801',
    year: 1981, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The PC-8801 became the definitive platform for Japanese RPGs and visual novels throughout the 1980s, with 64 KB of RAM enabling rich storytelling and vibrant graphics.',
    imageUrl: WC('NEC_PC-8801.jpg'),
  },
  {
    id: 'sharp_x1',
    name: 'Sharp X1',
    year: 1982, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Sharp\'s X1 had no built-in BASIC at all — you had to load Hu-BASIC from cassette tape every single time you turned it on. Purists loved it for exactly that reason!',
    imageUrl: WC('SHARP_PA-X1.jpg'),
  },
  {
    id: 'fujitsu_fm7',
    name: 'Fujitsu FM-7',
    year: 1982, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The FM-7 used two separate 6809 CPUs — one for programs, one dedicated entirely to graphics. A bold dual-processor design for a 64 KB home computer in 1982!',
    imageUrl: WC('FM-New7_May_2013_B.jpg'),
  },
  {
    id: 'turbografx_cd',
    name: 'TurboGrafx-CD',
    year: 1988, category: 'cartridge',
    spec: 65536,
    specLabel: '65,536 bytes buffer RAM',
    speech: 'number of bytes of buffer RAM',
    factoid: 'The TurboGrafx-CD was the world\'s first CD-ROM game system, adding 64 KB of RAM to stream from a 650 MB disc — a 10,000× storage leap over a typical cartridge!',
    imageUrl: WC('TurboGrafx-CD-Bare.jpg'),
  },
  {
    id: 'msx2',
    name: 'MSX2',
    year: 1985, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes video RAM',
    speech: 'number of bytes of video RAM',
    factoid: 'MSX2 standardized 128 KB of VRAM across all manufacturers — four times the original — enabling screen modes with up to 256 simultaneous colors on any MSX2 machine.',
    imageUrl: WC('Philips_NMS8250_MSX2_front.JPG'),
  },
  {
    id: 'msx2plus',
    name: 'MSX2+',
    year: 1988, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes video RAM',
    speech: 'number of bytes of video RAM',
    factoid: 'The MSX2+ added the Yamaha V9958 chip to its 128 KB of VRAM, enabling natural-color mode and smooth horizontal scrolling for the first time on MSX hardware.',
    imageUrl: WC('MSX_FS-A1WX.JPG'),
  },
  {
    id: 'nec_pc9801',
    name: 'NEC PC-9801',
    year: 1982, category: 'computer',
    spec: 131072,
    specLabel: '131,072 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The PC-9801 dominated Japanese business computing for over a decade with its unique 128 KB architecture — forming a Japan-exclusive PC ecosystem incompatible with Western IBM PCs.',
    imageUrl: WC('NEC_PC-9801_RX_Personal_Computer.jpg'),
  },
  {
    id: 'sharp_x68000_colors',
    name: 'Sharp X68000',
    year: 1987, category: 'monitor',
    spec: 65536,
    specLabel: '65,536 color palette',
    speech: 'total number of colors in the palette',
    factoid: 'Japan\'s X68000 displayed all 65,536 colors simultaneously at 512×512. It was so close to arcade hardware that Capcom used it as a development machine for Street Fighter II!',
    imageUrl: WC('X68000ACE-HD.JPG'),
  },
  {
    id: 'fujitsu_fm_towns',
    name: 'Fujitsu FM Towns',
    year: 1989, category: 'computer',
    spec: 1048576,
    specLabel: '1,048,576 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The FM Towns was Japan\'s first computer with a built-in CD-ROM drive as standard. Its 1 MB of RAM and 386 CPU made it a multimedia powerhouse for 1989.',
    imageUrl: WC('Fujitsu_FM_Towns_(1).jpg'),
  },

  // ── NINTENDO HARDWARE ────────────────────────────────────────
  {
    id: 'nes_wram',
    name: 'NES Work RAM',
    year: 1983, category: 'chip',
    spec: 2048,
    specLabel: '2,048 bytes RAM',
    speech: 'number of bytes of work RAM',
    factoid: 'The NES CPU had just 2 KB of internal RAM to track game state, enemies, and player data — Super Mario Bros. squeezed an entire kingdom into those 2,048 bytes!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'nes_chr_rom',
    name: 'NES CHR-ROM Bank',
    year: 1983, category: 'cartridge',
    spec: 8192,
    specLabel: '8,192 bytes CHR-ROM',
    speech: 'number of bytes in a character ROM bank',
    factoid: 'NES cartridges stored tile graphics in 8 KB CHR-ROM banks. The PPU read tiles directly from the cartridge — no RAM copy needed — saving precious memory for gameplay!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'nes_screen_width',
    name: 'NES Screen Width',
    year: 1983, category: 'monitor',
    spec: 256,
    specLabel: '256 px screen width',
    speech: 'screen width in pixels',
    factoid: 'The NES PPU rendered exactly 256 pixels per scanline. Combined with 240 rows, those 61,440 pixels hosted some of the most iconic game worlds ever drawn!',
    imageUrl: WC('NES-Console-Set.jpg'),
  },
  {
    id: 'gameboy_ram',
    name: 'Game Boy Work RAM',
    year: 1989, category: 'chip',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of internal RAM',
    factoid: 'The original Game Boy had just 8 KB of work RAM — yet Pokémon Red and Blue crammed 151 species, a whole overworld, and two rival trainers into its tiny memory!',
    imageUrl: WC('Game-Boy-FL.jpg'),
  },
  {
    id: 'sgb_border_colors',
    name: 'Super Game Boy Border',
    year: 1994, category: 'monitor',
    spec: 64,
    specLabel: '64 border colors',
    speech: 'number of colors in the TV border frame',
    factoid: 'The Super Game Boy cartridge for SNES let developers paint a custom TV border with up to 64 colors — turning a handheld game into a full living-room experience!',
    imageUrl: WC('Nintendo-Super-Game-Boy.jpg'),
  },
  {
    id: 'gbc_ram',
    name: 'Game Boy Color RAM',
    year: 1998, category: 'chip',
    spec: 32768,
    specLabel: '32,768 bytes RAM',
    speech: 'number of bytes of work RAM',
    factoid: 'The Game Boy Color had 32 KB of RAM — four times the original! That headroom let developers build richer RPGs and action games in the same compact shell.',
    imageUrl: WC('Game-Boy-Color-Purple.jpg'),
  },
  {
    id: 'snes_sound_ram',
    name: 'SNES SPC700 Audio RAM',
    year: 1990, category: 'chip',
    spec: 65536,
    specLabel: '65,536 bytes audio RAM',
    speech: 'number of bytes of audio RAM',
    factoid: 'The SNES SPC700 had its own sealed 64 KB of RAM. Composers like Koji Kondo and Yasunori Mitsuda had to fit every instrument sample and entire music score into that one block!',
    imageUrl: WC('SNES-Mod1-Console-Set.jpg'),
  },
  {
    id: 'virtualboy_wram',
    name: 'Virtual Boy Work RAM',
    year: 1995, category: 'chip',
    spec: 65536,
    specLabel: '65,536 bytes work RAM',
    speech: 'number of bytes of work RAM',
    factoid: 'The Virtual Boy\'s 64 KB of PSRAM needed 200 microseconds to stabilize after power-on — a quirk developers had to carefully account for in every game they shipped!',
    imageUrl: WC('Virtual-Boy-Set.jpg'),
  },
  {
    id: 'gba_ewram',
    name: 'Game Boy Advance RAM',
    year: 2001, category: 'chip',
    spec: 262144,
    specLabel: '262,144 bytes external RAM',
    speech: 'number of bytes of external work RAM',
    factoid: 'The GBA had 256 KB of external EWRAM plus 32 KB of faster internal chip RAM. Most game logic lived in EWRAM while time-critical code sprinted in the speedy internal RAM!',
    imageUrl: WC('Wikipedia_gameboyadvance.jpg'),
  },
  {
    id: 'gba_palette',
    name: 'Game Boy Advance Colors',
    year: 2001, category: 'monitor',
    spec: 32768,
    specLabel: '32,768 possible colors',
    speech: 'total number of colors in the palette',
    factoid: 'The GBA\'s 15-bit RGB palette offered 32,768 possible colors — matching the SNES — on a handheld you could slip in your pocket. Pokémon Ruby and Sapphire never looked so vibrant!',
    imageUrl: WC('Wikipedia_gameboyadvance.jpg'),
  },
  {
    id: 'gba_screen_height',
    name: 'Game Boy Advance Screen',
    year: 2001, category: 'monitor',
    spec: 160,
    specLabel: '160 px screen height',
    speech: 'screen height in pixels',
    factoid: 'The GBA\'s 240×160 screen was wider and shorter than the Game Boy Color — perfect for cinematic side-scrollers like Castlevania: Aria of Sorrow and Metroid Fusion!',
    imageUrl: WC('Wikipedia_gameboyadvance.jpg'),
  },
  {
    id: 'gba_total_pixels',
    name: 'Game Boy Advance Display',
    year: 2001, category: 'monitor',
    spec: 38400,
    specLabel: '38,400 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'At 240×160, the GBA screen had 38,400 pixels — nearly five times more than the original Game Boy — letting it render Mode 7-style effects from your belt clip!',
    imageUrl: WC('Wikipedia_gameboyadvance.jpg'),
  },
  {
    id: 'nintendo_ds_ram',
    name: 'Nintendo DS',
    year: 2004, category: 'chip',
    spec: 4194304,
    specLabel: '4,194,304 bytes RAM',
    speech: 'number of bytes of main RAM',
    factoid: 'The Nintendo DS packed 4 MB of RAM into a clamshell handheld with two screens. It became the second best-selling gaming device of all time with over 154 million units sold!',
    imageUrl: WC('Nintendo_DS_Default.PNG'),
  },
  {
    id: 'zelda_oot_cart',
    name: 'Zelda: Ocarina of Time Cart',
    year: 1998, category: 'cartridge',
    spec: 33554432,
    specLabel: '33,554,432 bytes ROM',
    speech: 'number of bytes of ROM',
    factoid: 'Ocarina of Time shipped on a 256-megabit (32 MB) cartridge — Nintendo\'s largest at launch. Every byte was needed to store Hyrule\'s temples, cutscenes, and orchestral samples!',
    imageUrl: WC('Legend_of_Zelda_Ocarina_of_Time.jpg'),
  },

  // ── SEGA HARDWARE ────────────────────────────────────────────
  {
    id: 'sc3000_ram',
    name: 'Sega SC-3000',
    year: 1983, category: 'computer',
    spec: 2048,
    specLabel: '2,048 bytes built-in RAM',
    speech: 'number of bytes of built-in RAM',
    factoid: 'Sega\'s first home computer launched the same day as the SG-1000 in 1983! It shipped with just 2 KB of built-in RAM, but BASIC cartridges could expand it up to 32 KB.',
    imageUrl: WC('Sega_SC-3000.jpg'),
  },
  {
    id: 'sms_ram',
    name: 'Sega Master System RAM',
    year: 1985, category: 'computer',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Master System launched with 8 KB of RAM in a single NEC chip. Remarkably, the Game Gear Sega released five years later used the exact same amount!',
    imageUrl: WC('Sega-Master-System-Set.jpg'),
  },
  {
    id: 'sega_gamegear_ram',
    name: 'Sega Game Gear RAM',
    year: 1990, category: 'computer',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Game Gear was essentially a portable Master System — same 8 KB RAM, same Z80 CPU, same sound chip. Its color screen was gorgeous but devoured six AA batteries in under three hours!',
    imageUrl: WC('Sega-Game-Gear-FR.jpg'),
  },
  {
    id: 'sms_palette',
    name: 'Master System Color Palette',
    year: 1985, category: 'monitor',
    spec: 64,
    specLabel: '64 color palette',
    speech: 'total number of colors in the palette',
    factoid: 'The Master System\'s 6-bit RGB palette held 64 possible colors — 16 for sprites and 16 for backgrounds simultaneously. Clever raster tricks could squeeze all 64 onto one screen!',
    imageUrl: WC('Sega-Master-System-Set.jpg'),
  },
  {
    id: 'sms_alexkidd_rom',
    name: 'Alex Kidd Built-In ROM',
    year: 1990, category: 'cartridge',
    spec: 65536,
    specLabel: '65,536 bytes ROM',
    speech: 'number of bytes of built-in ROM',
    factoid: 'Sega baked 64 KB of Alex Kidd in Miracle World directly into the Master System II\'s BIOS chip — so the console could play a full game with absolutely no cartridge inserted!',
    imageUrl: WC('Sega-Master-System-II-Bare.jpg'),
  },
  {
    id: 'sega_pico_ram',
    name: 'Sega Pico',
    year: 1993, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Sega Pico was a toddler-friendly "edutainment" console with a built-in drawing pad and stylus. Its 64 KB of RAM powered learning games for children aged 3 to 7!',
    imageUrl: WC('Closed_Sega_Pico.jpg'),
  },
  {
    id: 'sms_resolution',
    name: 'Master System Display',
    year: 1985, category: 'monitor',
    spec: 49152,
    specLabel: '49,152 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'The Master System\'s 256×192 screen packed 49,152 pixels — the same resolution as MSX and ColecoVision. Sega just filled every one of them with more colorful action!',
    imageUrl: WC('Sega-Master-System-Set.jpg'),
  },
  {
    id: 'sega_nomad_pixels',
    name: 'Sega Nomad Screen',
    year: 1995, category: 'monitor',
    spec: 71680,
    specLabel: '71,680 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'The Genesis Nomad\'s 3.25-inch LCD ran at 320×224 — matching the home Genesis exactly. It was the first handheld to play full 16-bit cartridges at native resolution!',
    imageUrl: WC('Sega-Genesis-Nomad-Console-04.jpg'),
  },
  {
    id: 'sega_32x_ram',
    name: 'Sega 32X',
    year: 1994, category: 'computer',
    spec: 262144,
    specLabel: '262,144 bytes RAM',
    speech: 'number of bytes of program RAM',
    factoid: 'The 32X mushroomed out of the Genesis cartridge slot with two SH-2 processors and 256 KB of RAM. Developers had to coordinate four CPUs — a nightmare that limited the library to 40 games!',
    imageUrl: WC('Sega-Genesis-32X-01.jpg'),
  },
  {
    id: 'sega_megacd_ram',
    name: 'Sega Mega-CD',
    year: 1991, category: 'computer',
    spec: 524288,
    specLabel: '524,288 bytes RAM',
    speech: 'number of bytes of program RAM',
    factoid: 'The Mega-CD add-on gave the Genesis 512 KB of extra RAM and a CD-ROM drive. Developers had to juggle three CPUs and three separate memory pools to unlock its full power!',
    imageUrl: WC('Sega-CD-Model1-Set.jpg'),
  },
  {
    id: 'sega_saturn_ram',
    name: 'Sega Saturn',
    year: 1994, category: 'computer',
    spec: 2097152,
    specLabel: '2,097,152 bytes Work RAM',
    speech: 'number of bytes of Work RAM',
    factoid: 'The Saturn split its 2 MB of RAM into "fast" and "slow" banks across its dual-CPU design. Mastering both unlocked some of the most jaw-dropping 2D sprite work of the 32-bit era!',
    imageUrl: WC('Sega-Saturn-Console-Set-Mk2.jpg'),
  },
  {
    id: 'sega_saturn_vram',
    name: 'Sega Saturn Video RAM',
    year: 1994, category: 'chip',
    spec: 1572864,
    specLabel: '1,572,864 bytes video RAM',
    speech: 'number of bytes of video RAM',
    factoid: 'The Saturn split its 1.5 MB of VRAM across two VDP chips: VDP1 handled sprites and polygons while VDP2 drew scrolling backgrounds — together powering Virtua Fighter 2 at home!',
    imageUrl: WC('Sega-Saturn-Console-Set-Mk2.jpg'),
  },
  {
    id: 'sega_dreamcast_ram',
    name: 'Sega Dreamcast',
    year: 1998, category: 'computer',
    spec: 16777216,
    specLabel: '16,777,216 bytes RAM',
    speech: 'number of bytes of main RAM',
    factoid: 'With 16 MB of RAM and the world\'s first built-in modem on a home console, the Dreamcast pioneered online gaming in 1998 — years before Xbox Live or PlayStation Network.',
    imageUrl: WC('Sega-dreamcast-set.png'),
  },
  {
    id: 'sega_dreamcast_vram',
    name: 'Dreamcast Video RAM',
    year: 1998, category: 'chip',
    spec: 8388608,
    specLabel: '8,388,608 bytes video RAM',
    speech: 'number of bytes of video RAM',
    factoid: 'The Dreamcast\'s PowerVR2 GPU had 8 MB of video RAM using tile-based deferred rendering — a technique so efficient that modern smartphone GPUs still use the same approach today!',
    imageUrl: WC('Sega-dreamcast-set.png'),
  },

  // ── OTHER CONSOLES ───────────────────────────────────────────
  {
    id: 'odyssey_300',
    name: 'Magnavox Odyssey 300',
    year: 1976, category: 'computer',
    spec: 3,
    specLabel: '3 built-in games',
    speech: 'number of built-in games',
    factoid: 'The Odyssey 300 had three built-in games: Tennis, Hockey, and Smash — no cartridges, no CPU, just pure analog circuitry in a wood-grain box!',
    imageUrl: WC('Magnavox-Odyssey-300.jpg'),
  },
  {
    id: 'jaguar_tom_mhz',
    name: 'Atari Jaguar "Tom" GPU',
    year: 1993, category: 'chip',
    spec: 26,
    specLabel: '26 MHz clock speed',
    speech: 'clock speed in megahertz',
    factoid: 'Tom, the Jaguar\'s main graphics chip, ran at 26 MHz and combined a GPU, object processor, and 64-bit blitter in one package — the heart of Atari\'s "64-bit" marketing claim!',
    imageUrl: WC('Atari-Jaguar-Console-Set.jpg'),
  },
  {
    id: 'atari7800_colors',
    name: 'Atari 7800 ProSystem',
    year: 1984, category: 'monitor',
    spec: 25,
    specLabel: '25 colors per scanline',
    speech: 'number of colors displayable on a single scanline',
    factoid: 'The Atari 7800 could show 25 colors on each scanline. Clever programmers changed the palette between scanlines to sneak even more colors into a single scene!',
    imageUrl: WC('Atari-7800-Console.jpg'),
  },
  {
    id: 'entex_av_leds',
    name: 'Entex Adventure Vision',
    year: 1982, category: 'monitor',
    spec: 40,
    specLabel: '40 red LEDs',
    speech: 'number of red LEDs in the display column',
    factoid: 'The Adventure Vision used just 40 red LEDs and a spinning mirror to fake a 150×40 display — one of the rarest and most unusual handheld consoles of the early 1980s!',
    imageUrl: WC('Entex_Adventure_Vision.jpg'),
  },
  {
    id: 'neo_geo_pocket_battery',
    name: 'Neo Geo Pocket Color',
    year: 1998, category: 'computer',
    spec: 40,
    specLabel: '40 hours battery life',
    speech: 'battery life in hours',
    factoid: 'The Neo Geo Pocket Color ran for an incredible 40 hours on two AA batteries — more than twice the Game Boy Color. SNK called its premium joystick a "thumb joypad"!',
    imageUrl: WC('Neo-Geo-Pocket-Color-Blue.jpg'),
  },
  {
    id: 'hartung_game_master_ram',
    name: 'Hartung Game Master',
    year: 1990, category: 'computer',
    spec: 2048,
    specLabel: '2,048 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Hartung Game Master was a little-known German handheld with just 2 KB of RAM and a 64×64 LCD. It competed against the Game Boy as a true footnote in gaming history!',
    imageUrl: WC('Hartung_Game_Master.jpg'),
  },
  {
    id: 'vectrex_ram',
    name: 'GCE Vectrex',
    year: 1982, category: 'computer',
    spec: 1024,
    specLabel: '1,024 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Vectrex used a real vector display — no pixels, just glowing lines — and drew entire games with just 1 KB of RAM. It even shipped with a built-in game: Mine Storm!',
    imageUrl: WC('GCE-Vectrex-Console.jpg'),
  },
  {
    id: 'watara_supervision_ram',
    name: 'Watara Supervision',
    year: 1992, category: 'computer',
    spec: 8192,
    specLabel: '8,192 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Watara Supervision sold for just $49 — half the price of a Game Boy! Its 8 KB of RAM and a link cable for two-player gaming made it the budget handheld of the early 90s.',
    imageUrl: WC('Watara-Supervision.jpg'),
  },
  {
    id: 'mattel_aquarius_ram',
    name: 'Mattel Aquarius',
    year: 1983, category: 'computer',
    spec: 4096,
    specLabel: '4,096 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Mattel\'s own engineers reportedly nicknamed the Aquarius the "System of the Seventies." With just 4 KB of RAM it was already outdated in 1983 and was discontinued after only four months!',
    imageUrl: WC('Mattel-Aquarius.jpg'),
  },
  {
    id: 'apf_mp1000_games',
    name: 'APF MP1000',
    year: 1978, category: 'computer',
    spec: 13,
    specLabel: '13 total games released',
    speech: 'number of games ever released',
    factoid: 'The APF MP1000 had one of the smallest game libraries of any console — just 13 games total. Its real legacy was the add-on keyboard that turned it into a fully functional home computer!',
    imageUrl: WC('APF-MP1000-Console.jpg'),
  },
  {
    id: 'atari5200_ram',
    name: 'Atari 5200 SuperSystem',
    year: 1982, category: 'computer',
    spec: 16384,
    specLabel: '16,384 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Atari 5200 had 128× more RAM than the 2600 it replaced — but its non-centering joysticks and lack of backward compatibility made it a flop despite impressive hardware!',
    imageUrl: WC('Atari-5200-4P-Set.jpg'),
  },
  {
    id: 'neo_geo_aes_ram',
    name: 'Neo Geo AES',
    year: 1990, category: 'computer',
    spec: 65536,
    specLabel: '65,536 bytes work RAM',
    speech: 'number of bytes of work RAM',
    factoid: 'SNK\'s Neo Geo AES launched at $649 — nearly $1,500 today. Its 64 KB of work RAM and arcade-identical hardware finally gave home players the true coin-op experience.',
    imageUrl: WC('Neo-Geo-AES-Console.jpg'),
  },
  {
    id: 'arcadia_2001_ram',
    name: 'Emerson Arcadia 2001',
    year: 1982, category: 'computer',
    spec: 1024,
    specLabel: '1,024 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'Emerson falsely claimed the Arcadia 2001 had 24 KB of RAM in advertisements — it actually had just 1 KB! The false advertising scandal helped doom the console.',
    imageUrl: WC('Emerson-Arcadia-2001-Console.jpg'),
  },
  {
    id: 'jaguar_ram',
    name: 'Atari Jaguar RAM',
    year: 1993, category: 'computer',
    spec: 2097152,
    specLabel: '2,097,152 bytes RAM',
    speech: 'number of bytes of RAM',
    factoid: 'The Atari Jaguar packed 2 MB of fast RAM on a 64-bit bus — Atari\'s last console ever made. Despite powerful specs, only about 50 games were released before Atari shut down in 1996.',
    imageUrl: WC('Atari-Jaguar-Console-Set.jpg'),
  },
  {
    id: 'neo_geo_cd_ram',
    name: 'Neo Geo CD',
    year: 1994, category: 'computer',
    spec: 7340032,
    specLabel: '7,340,032 bytes RAM',
    speech: 'total system RAM in bytes',
    factoid: 'The Neo Geo CD had 7 MB of RAM to compensate for its agonizingly slow single-speed CD drive — loading times of 30–60 seconds per stage became a running joke among fans!',
    imageUrl: WC('Neo-Geo-CD-TopLoading.jpg'),
  },

  // ── DISPLAY & GRAPHICS STANDARDS ─────────────────────────────
  {
    id: 'tandy_tga_colors',
    name: 'Tandy Graphics Adapter',
    year: 1984, category: 'monitor',
    spec: 16,
    specLabel: '16 colors at 160×200',
    speech: 'number of colors in 160×200 mode',
    factoid: 'The Tandy 1000 cloned the IBM PCjr\'s graphics chip and sold it in Radio Shack stores. Its 16-color 160×200 mode made it the best PC for games before VGA arrived!',
    imageUrl: WC('Tandy_1000_computer_original.jpg'),
  },
  {
    id: 'amiga_lores_pixels',
    name: 'Amiga OCS Lo-Res Mode',
    year: 1985, category: 'monitor',
    spec: 64000,
    specLabel: '64,000 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'The Amiga\'s 320×200 lo-res mode packed 64,000 pixels with up to 32 colors and butter-smooth animations that left the PC market stunned in 1985!',
    imageUrl: WC('Amiga500_system.jpg'),
  },
  {
    id: 'snes_screen_width',
    name: 'SNES Screen Width',
    year: 1990, category: 'monitor',
    spec: 256,
    specLabel: '256 px screen width',
    speech: 'screen width in pixels',
    factoid: 'Like the NES before it, the SNES also output exactly 256 pixels wide — but packed in 32,768 colors, Mode 7 rotation, and 128 sprites to make it look like a leap into the future!',
    imageUrl: WC('SNES-Mod1-Console-Set.jpg'),
  },
  {
    id: 'qvga_pixels',
    name: 'QVGA Display Standard',
    year: 1999, category: 'monitor',
    spec: 76800,
    specLabel: '76,800 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'Quarter-VGA\'s 320×240 screen packed exactly 76,800 pixels into early smartphones and PDAs — one quarter the area of a full VGA screen, as the name implies!',
    imageUrl: WC('Nokia_6230i.jpg'),
  },
  {
    id: 'amiga_hires_pixels',
    name: 'Amiga OCS Hi-Res Mode',
    year: 1985, category: 'monitor',
    spec: 128000,
    specLabel: '128,000 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'Amiga\'s hi-res 640×200 mode doubled horizontal pixels to 128,000 total — ideal for desktop publishing. The Amiga was a DTP powerhouse years before Windows existed!',
    imageUrl: WC('Amiga_1000DP.jpg'),
  },
  {
    id: 'cga_hires_mono',
    name: 'CGA Hi-Res Monochrome',
    year: 1981, category: 'monitor',
    spec: 128000,
    specLabel: '128,000 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'CGA Mode 6\'s 640×200 monochrome mode gave 128,000 pixels of detail. Programmers used it for games like SimCity where sharp outlines mattered more than color.',
    imageUrl: WC('CGA_Display_Version_2.png'),
  },
  {
    id: 'hvga_pixels',
    name: 'HVGA Display (iPhone 1st gen)',
    year: 2007, category: 'monitor',
    spec: 153600,
    specLabel: '153,600 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'Half-VGA\'s 480×320 screen with 153,600 pixels powered the original iPhone. Steve Jobs called it "the best mobile display in the world" at launch in January 2007!',
    imageUrl: WC('IPhone_1st_Gen.svg'),
  },
  {
    id: 'hercules_hgc',
    name: 'Hercules Graphics Card',
    year: 1982, category: 'monitor',
    spec: 250560,
    specLabel: '250,560 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'The Hercules card crammed 720×348 monochrome pixels onto IBM PCs that officially had no graphics mode at all — bootleg brilliance that became a genuine bestseller!',
    imageUrl: WC('KL_Hercules_HGC.jpg'),
  },
  {
    id: 'mda_resolution',
    name: 'IBM MDA Display',
    year: 1981, category: 'monitor',
    spec: 252000,
    specLabel: '252,000 addressable pixels',
    speech: 'total number of addressable character pixels',
    factoid: 'The MDA shipped on day one with the IBM PC in 1981. Its 720×350 text grid was so crisp it made competing color cards look blurry for years.',
    imageUrl: WC('IBM_5151_MDA_monitor.jpg'),
  },
  {
    id: 'atari_st_hires',
    name: 'Atari ST Hi-Res Mono Mode',
    year: 1985, category: 'monitor',
    spec: 256000,
    specLabel: '256,000 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'The Atari ST\'s 640×400 monochrome mode required a special 72 Hz monitor — but gave musicians and desktop publishers a razor-sharp 256,000-pixel workspace!',
    imageUrl: WC('Atari_520ST_with_SM124_monitor.jpg'),
  },
  {
    id: 'xga_resolution',
    name: 'IBM XGA Standard',
    year: 1990, category: 'monitor',
    spec: 786432,
    specLabel: '786,432 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'IBM\'s Extended Graphics Array brought 1024×768 to workstations in 1990. That 786,432-pixel canvas became the classroom projector and office monitor standard for two decades!',
    imageUrl: WC('MCA_IBM_XGA-2.jpg'),
  },
  {
    id: 'wxga_resolution',
    name: 'WXGA Widescreen Standard',
    year: 2003, category: 'monitor',
    spec: 1024000,
    specLabel: '1,024,000 total pixels',
    speech: 'total number of pixels on screen',
    factoid: 'WXGA\'s 1280×800 resolution (exactly 1,024,000 pixels) became the defining laptop display of the mid-2000s — just barely crossing the one-million-pixel threshold!',
    imageUrl: WC('Laptop_screen_detail_glossy.jpg'),
  },

  // ── STORAGE MEDIA ────────────────────────────────────────────
  {
    id: 'sony_mavica',
    name: 'Sony Mavica',
    year: 1981, category: 'cartridge',
    spec: 50,
    specLabel: '50 images per disk',
    speech: 'number of still images per disk',
    factoid: 'Sony\'s 1981 Mavica prototype was the world\'s first electronic still camera. Its 2-inch "Mavipak" floppy stored exactly 50 analog video frames — no film, no darkroom needed.',
    imageUrl: WC('Mavica_MVC-A7AF.jpg'),
  },
  {
    id: 'floppy_8inch',
    name: '8-Inch Floppy Disk',
    year: 1971, category: 'cartridge',
    spec: 81920,
    specLabel: '81,920 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'IBM\'s original 8-inch "memory disk" of 1971 was read-only and held 80 KB — equivalent to about 3,000 punched cards. It launched the entire removable-disk era.',
    imageUrl: WC('8-inch_floppy_disk.jpg'),
  },
  {
    id: 'commodore_1541',
    name: 'Commodore 1541 Floppy',
    year: 1982, category: 'cartridge',
    spec: 174848,
    specLabel: '174,848 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'The legendarily slow 1541 drive had a serial bus so inefficient that a hardware speed-up mod was a top-selling accessory. Its 174,848 bytes came from 683 sectors of 256 bytes each.',
    imageUrl: WC('Commodore-1541-Floppy-Drive.jpg'),
  },
  {
    id: 'fds_disk',
    name: 'Famicom Disk System',
    year: 1986, category: 'cartridge',
    spec: 57344,
    specLabel: '57,344 bytes per disk side',
    speech: 'storage capacity per disk side in bytes',
    factoid: 'Nintendo\'s Famicom Disk System stored 56 KB per disk side. The Legend of Zelda debuted on a double-sided disk — battery-backed saves for an entire open world!',
    imageUrl: WC('Famicom-Disk-System-set.jpg'),
  },
  {
    id: 'floppy_35hd',
    name: '3.5" HD Floppy Disk',
    year: 1987, category: 'cartridge',
    spec: 1474560,
    specLabel: '1,474,560 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'Marketed as "1.44 MB," this disk actually holds 1,474,560 bytes — neither a decimal nor binary megabyte. The misleading label has confused computer students ever since!',
    imageUrl: WC('Floppy_disk_2009_G1.jpg'),
  },
  {
    id: 'pc98_floppy',
    name: 'NEC PC-98 Floppy',
    year: 1982, category: 'cartridge',
    spec: 1261568,
    specLabel: '1,261,568 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'NEC\'s PC-98 used a unique "1232 KB" floppy format incompatible with IBM PCs. This quirk helped the PC-98 dominate Japan\'s business market throughout the 1990s.',
    imageUrl: WC('NEC_PC-9801_RX_Personal_Computer.jpg'),
  },
  {
    id: 'floppy_288mb',
    name: '2.88 MB ED Floppy Disk',
    year: 1992, category: 'cartridge',
    spec: 2949120,
    specLabel: '2,949,120 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'IBM\'s Extended Density floppy doubled the HD disk\'s capacity using barium ferrite magnetic particles — but at $10 per disk it was too expensive and barely sold.',
    imageUrl: WC('Floppy_disk_2009_G1.jpg'),
  },
  {
    id: 'zip100',
    name: 'Iomega Zip Disk 100',
    year: 1994, category: 'cartridge',
    spec: 100663296,
    specLabel: '100,663,296 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'The Zip disk\'s "100 MB" was actually 100,663,296 bytes. At its peak, Iomega sold 100 million Zip drives and became a household name for removable storage in the 1990s.',
    imageUrl: WC('Iomega-Zip-100-Attachment.jpg'),
  },
  {
    id: 'cdrom',
    name: 'CD-ROM',
    year: 1982, category: 'cartridge',
    spec: 681574400,
    specLabel: '681,574,400 bytes',
    speech: 'storage capacity in bytes',
    factoid: 'The CD\'s 74-minute capacity was reportedly set so Beethoven\'s 9th Symphony fit on one disc. A single CD holds 681,574,400 bytes — 200,000 times larger than an Atari 2600 cartridge!',
    imageUrl: WC('CD_autolev_crop.jpg'),
  },

  // ── SOUND CHIPS ──────────────────────────────────────────────
  {
    id: 'sid_6581',
    name: 'Commodore SID 6581',
    year: 1982, category: 'chip',
    spec: 3,
    specLabel: '3 voices',
    speech: 'number of oscillator voices',
    factoid: 'Designed by Bob Yannes in just five months, the SID\'s 3 voices each had their own ADSR envelope, filter, and four waveform shapes. The "SID scene" still releases new chip music today!',
    imageUrl: WC('MOS_6581_Chip.jpg'),
  },
  {
    id: 'ym2612',
    name: 'Yamaha YM2612 (OPN2)',
    year: 1988, category: 'chip',
    spec: 6,
    specLabel: '6 FM channels',
    speech: 'number of FM sound channels',
    factoid: 'The Sega Genesis\'s YM2612 had 6 four-operator FM channels — channel 6 could switch to PCM sample playback. Its characteristic lo-fi distortion became the sonic identity of 16-bit gaming.',
    imageUrl: WC('Yamaha_YM2612.jpg'),
  },
  {
    id: 'snes_spc700',
    name: 'SNES SPC700 / S-DSP',
    year: 1990, category: 'chip',
    spec: 8,
    specLabel: '8 audio channels',
    speech: 'number of audio channels',
    factoid: 'Sony built the SPC700 DSP for Nintendo\'s SNES. Its 8 PCM channels with ADSR envelopes, echo, and a reverb filter gave SNES music a warmth no previous game chip had achieved.',
    imageUrl: WC('SNES-Mod1-Console-Set.jpg'),
  },
  {
    id: 'opl2_ym3812',
    name: 'Yamaha OPL2 (YM3812)',
    year: 1985, category: 'chip',
    spec: 9,
    specLabel: '9 FM channels',
    speech: 'number of FM sound channels',
    factoid: 'The YM3812 powered the AdLib card and original Sound Blaster. Its 9 two-operator FM channels became the PC sound standard — every late-80s game was tuned specifically for it.',
    imageUrl: WC('Yamaha_YM3812.jpg'),
  },
  {
    id: 'roland_mt32',
    name: 'Roland MT-32',
    year: 1987, category: 'chip',
    spec: 32,
    specLabel: '32 simultaneous partials',
    speech: 'number of simultaneous sound partials',
    factoid: 'The MT-32\'s LA synthesis combined PCM samples with digital oscillators into 32 simultaneous partials. Sierra and LucasArts wrote special MT-32 soundtracks that made games sound like real instruments in 1987.',
    imageUrl: WC('Roland_MT-32_Module.jpg'),
  },
  {
    id: 'general_midi',
    name: 'General MIDI Standard',
    year: 1991, category: 'chip',
    spec: 128,
    specLabel: '128 standard instruments',
    speech: 'number of standardized instrument programs',
    factoid: 'General MIDI defined 128 instrument programs — from #1 Acoustic Grand Piano to #128 Gunshot — so MIDI files would sound the same on any compliant device worldwide.',
    imageUrl: WC('MIDI_logo.svg'),
  },
  {
    id: 'opl3_ymf262',
    name: 'Yamaha OPL3 (YMF262)',
    year: 1990, category: 'chip',
    spec: 18,
    specLabel: '18 FM channels',
    speech: 'number of FM sound channels',
    factoid: 'The OPL3 doubled the OPL2\'s 9 channels to 18, added stereo output and four new waveforms. The Sound Blaster Pro 2 made it the new DOS gaming standard almost overnight.',
    imageUrl: WC('Yamaha_YMF262.jpg'),
  },
];

// Validate all specs and attach placeValue
export const RETRO_OBJECTS: RetroObject[] = RAW.map(obj => ({
  ...obj,
  placeValue: getPlaceValueBin(obj.spec),
}));

// Helper: get objects valid for currently unlocked bins
export function getObjectsForBins(unlockedBins: string[]): RetroObject[] {
  return RETRO_OBJECTS.filter(obj => unlockedBins.includes(obj.placeValue));
}

// Weighted-random object picker (avoids repeating last 3)
export function pickNextObject(
  unlockedBins: string[],
  recentIds: string[] = []
): RetroObject {
  const pool = getObjectsForBins(unlockedBins).filter(o => !recentIds.includes(o.id));
  if (pool.length === 0) return getObjectsForBins(unlockedBins)[0];
  return pool[Math.floor(Math.random() * pool.length)];
}
